#!/usr/bin/env python3
"""Retag a standard cp39-abi3 SUEWS wheel as the UMEP (NumPy<2) variant.

Replaces the separate cibuildwheel `build_umep` job by performing byte-level
wheel surgery on the existing abi3 wheel:

  - Rewrite ``supy/_version_scm.py`` with the UMEP version
    (``rc1`` for production, ``.dev(N+1)`` for nightly)
  - Rewrite ``METADATA``: ``Version`` + ``Requires-Dist: numpy<2.0,>=1.22``
  - Rename ``.dist-info/`` directory to match the new version
  - Regenerate ``RECORD`` with correct SHA256 hashes and sizes
  - Repack the zip with the new version in the filename

The wheel filename tags stay as ``cp39-abi3-<plat>`` — one retagged wheel per
platform covers cp39..cp3xx wherever NumPy 1.x wheels exist. This is an
explicit scope expansion from the prior cp312-only UMEP contract (QGIS 3 LTR
Windows only) to a general-purpose NumPy<2 compatibility line.

Usage::

    retag_umep_wheel.py <input_wheel> --out-dir <dir>
    retag_umep_wheel.py dist/*.whl --out-dir dist-umep/
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

WHEEL_NAME_RE = re.compile(
    r"^(?P<name>[^-]+)-(?P<version>[^-]+)-(?P<build>[^-]*-)?"
    r"(?P<python>[^-]+)-(?P<abi>[^-]+)-(?P<platform>[^-]+)\.whl$"
)

UMEP_NUMPY_CONSTRAINT = "numpy<2.0,>=1.22"


def transform_version(version: str) -> str:
    """Apply the UMEP version transformation.

    Mirrors the ``BUILD_UMEP_VARIANT`` branch in ``get_ver_git.py``:
    nightly (``.dev``) bumps the dev counter by one; production tags gain
    an ``rc1`` suffix.
    """
    if ".dev" in version:
        base, dev_num = version.rsplit(".dev", 1)
        return f"{base}.dev{int(dev_num) + 1}"
    return version + "rc1"


def parse_version_tuple(version_str: str) -> tuple:
    """Parse a version string into a tuple for ``_version_scm.py``.

    Mirrors ``get_ver_git.parse_version_tuple``. Kept in-sync manually —
    if get_ver_git.py changes, update here too.
    """
    parts = version_str.split(".")
    major = int(parts[0])
    minor = int(parts[1])
    patch_str = parts[2]
    suffix = None
    if "dev" in patch_str:
        patch, suffix = patch_str.split("dev", 1)
        patch = int(patch) if patch else 0
        suffix = "dev" + suffix
    elif "rc" in patch_str:
        patch, suffix = patch_str.split("rc", 1)
        patch = int(patch)
        suffix = "rc" + suffix
    else:
        patch = int(patch_str)
    if len(parts) > 3:
        suffix = parts[3]
    if suffix:
        return (major, minor, patch, suffix)
    return (major, minor, patch)


def render_version_file(version: str) -> str:
    return (
        "# file generated by `get_ver_git.py`\n"
        "# don't change, don't track in version control\n"
        f"__version__ = version = '{version}'\n"
        f"__version_tuple__ = version_tuple = {parse_version_tuple(version)}\n"
    )


def rewrite_metadata(raw: bytes, new_version: str) -> bytes:
    """Rewrite ``Version:`` and the NumPy ``Requires-Dist:`` line."""
    text = raw.decode("utf-8")

    text = re.sub(
        r"^Version:\s*\S+\s*$",
        f"Version: {new_version}",
        text,
        count=1,
        flags=re.MULTILINE,
    )

    numpy_dist_re = re.compile(
        r"^Requires-Dist:\s*numpy[^\r\n]*$",
        flags=re.MULTILINE,
    )
    if not numpy_dist_re.search(text):
        raise RuntimeError(
            "METADATA does not contain a Requires-Dist line for numpy — "
            "cannot apply UMEP constraint"
        )
    text = numpy_dist_re.sub(
        f"Requires-Dist: {UMEP_NUMPY_CONSTRAINT}",
        text,
        count=1,
    )

    return text.encode("utf-8")


def sha256_record_entry(data: bytes) -> str:
    digest = hashlib.sha256(data).digest()
    encoded = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return f"sha256={encoded}"


def regenerate_record(root: Path, record_relpath: Path) -> str:
    """Walk the staging tree and emit a fresh RECORD.

    The RECORD file itself appears with empty hash and size (standard pattern).
    """
    lines = []
    all_files = sorted(p for p in root.rglob("*") if p.is_file())
    for file_path in all_files:
        rel = file_path.relative_to(root)
        rel_str = rel.as_posix()
        if rel == record_relpath:
            lines.append(f"{rel_str},,")
            continue
        data = file_path.read_bytes()
        lines.append(f"{rel_str},{sha256_record_entry(data)},{len(data)}")
    return "\n".join(lines) + "\n"


def retag_one(input_wheel: Path, out_dir: Path) -> Path:
    match = WHEEL_NAME_RE.match(input_wheel.name)
    if not match:
        raise ValueError(f"Cannot parse wheel filename: {input_wheel.name}")
    name = match.group("name")
    old_version = match.group("version")
    new_version = transform_version(old_version)

    print(f"[retag] {input_wheel.name}")
    print(f"        {old_version} -> {new_version}")

    out_dir.mkdir(parents=True, exist_ok=True)
    output_name = input_wheel.name.replace(
        f"-{old_version}-", f"-{new_version}-", 1
    )
    output_wheel = out_dir / output_name

    with tempfile.TemporaryDirectory() as td:
        staging = Path(td)

        with zipfile.ZipFile(input_wheel) as zf:
            zf.extractall(staging)

        old_distinfo = staging / f"{name}-{old_version}.dist-info"
        new_distinfo = staging / f"{name}-{new_version}.dist-info"
        if not old_distinfo.is_dir():
            raise RuntimeError(f"dist-info not found: {old_distinfo}")

        # Rewrite METADATA (content change) before renaming the directory.
        metadata_path = old_distinfo / "METADATA"
        metadata_path.write_bytes(
            rewrite_metadata(metadata_path.read_bytes(), new_version)
        )

        # Rewrite the embedded version module.
        version_module = staging / "supy" / "_version_scm.py"
        if not version_module.is_file():
            raise RuntimeError(f"version module not found: {version_module}")
        version_module.write_text(render_version_file(new_version), encoding="utf-8")

        # Rename dist-info to match the new version.
        old_distinfo.rename(new_distinfo)

        # Regenerate RECORD after all other content changes.
        record_path = new_distinfo / "RECORD"
        record_rel = record_path.relative_to(staging)
        record_path.write_text(
            regenerate_record(staging, record_rel), encoding="utf-8"
        )

        # Repack with zip DEFLATE (matches cibuildwheel / meson-python output).
        if output_wheel.exists():
            output_wheel.unlink()
        with zipfile.ZipFile(output_wheel, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in sorted(staging.rglob("*")):
                if file_path.is_file():
                    zf.write(file_path, file_path.relative_to(staging).as_posix())

    print(f"        -> {output_wheel}")
    return output_wheel


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wheels", nargs="+", type=Path, help="Input .whl files")
    parser.add_argument(
        "--out-dir", type=Path, required=True, help="Output directory for retagged wheels"
    )
    args = parser.parse_args()

    for wheel in args.wheels:
        if not wheel.is_file():
            print(f"error: not a file: {wheel}", file=sys.stderr)
            return 2
        retag_one(wheel, args.out_dir)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
