# Pre-commit hooks for consistent code quality
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the formatter first
      - id: ruff-format
        name: Format Python code with ruff
        
      # Then run the linter
      - id: ruff
        name: Lint Python code with ruff
        args: [--fix, --exit-non-zero-on-fix]
        
  # Optional: Add other useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^test/.*\.txt$  # Exclude test data files
      - id: end-of-file-fixer
        exclude: ^test/.*\.txt$
      - id: check-yaml
        exclude: ^\.github/workflows/.*\.yml$  # GitHub Actions use special syntax
      - id: check-added-large-files
        args: ['--maxkb=5000']  # 5MB limit
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements  # Check for forgotten print/breakpoint