# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Build strategy: HTML is pre-built by CI (docs-sync workflow) and committed
# to the rtd branch. RTD just copies the pre-built output — no source builds,
# no Fortran compiler, no pip install needed.

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"  # Required by RTD v2 schema; not used for build
  commands:
    # Copy pre-built HTML to RTD output directory
    - |
      if [ ! -d docs/build/html ]; then
        echo "ERROR: Pre-built HTML not found. The docs-sync CI workflow must run first."
        exit 1
      fi
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/

# No Sphinx config needed — HTML is pre-built by CI
# No PDF or ePub
formats: []
