# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Build strategy: Aligned with GitHub Actions workflow
# - Uses system gfortran via apt (like GHA manylinux)
# - Uses uv for fast Python package management (installed into RTD virtualenv)
# - Standard non-editable install (RTD doesn't need -e flag)
# - Removed conda dependency for consistency with GHA build process

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - gfortran  # Fortran compiler for building from source
    - build-essential  # Ensure full build toolchain available
  jobs:
    pre_install:
      # Fetch all tags for proper version detection
      - git fetch --unshallow || true
      - git fetch --tags || true
      - git update-index --assume-unchanged docs/source/conf.py
    post_create_environment:
      # Install uv in the RTD virtualenv
      - python -m pip install uv
      # Install build dependencies
      - uv pip install wheel "numpy>=2.0" "meson-python>=0.17.0" "f90wrap==0.2.16"
      # Install package with dev extras
      - uv pip install ".[dev]"
    post_install:
      # Generate RST files after package is installed
      - cd docs && make generate-rst

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Build documentation formats
# Only HTML format (no PDF or ePub to avoid compatibility issues)
formats: []