# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Build strategy: Use pre-built wheels from PyPI instead of building from source
# - For formal releases: Use standard PyPI (pip install supy)
# - For dev versions: Use Test PyPI (pip install -i https://test.pypi.org/simple/ supy)
# - Much faster than building from source (~30 seconds vs 2-3 minutes)
# - No need for gfortran or build toolchain

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # Use 3.12 to match Test PyPI dev wheel builds
  jobs:
    pre_install:
      # Fetch all tags for proper version detection
      - git fetch --unshallow || true
      - git fetch --tags || true
      - git update-index --assume-unchanged docs/source/conf.py
    post_create_environment:
      # Detect version type and install appropriate pre-built wheel
      - |
        SUPY_VERSION=$(python get_ver_git.py 2>/dev/null || echo "unknown")
        echo "Detected SuPy version: $SUPY_VERSION"

        if [[ "$SUPY_VERSION" == *".dev"* ]] || [[ "$SUPY_VERSION" == "unknown" ]]; then
          echo "Installing dev version from Test PyPI..."
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ "supy[dev]"
        else
          echo "Installing release version from PyPI..."
          python -m pip install "supy[dev]"
        fi
    post_install:
      # Generate RST files after package is installed
      - cd docs && make generate-rst

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Build documentation formats
# Only HTML format (no PDF or ePub to avoid compatibility issues)
formats: []