# .readthedocs.yaml
# Read the Docs configuration file for the `docs` branch
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# This branch contains pre-built sphinx-gallery artefacts, so RTD only needs
# to render Sphinx (no tutorial execution, no gfortran compilation).
# Gallery is rebuilt in CI (docs-sync.yml) and committed to this branch.

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  # No apt_packages needed (no gfortran -- gallery is pre-built)
  jobs:
    pre_install:
      # Fetch all tags for proper version detection
      - git fetch --unshallow || true
      - git fetch --tags || true
      - git update-index --assume-unchanged docs/source/conf.py
    post_create_environment:
      # Pre-install Sphinx with upper bound (Sphinx 9.0 breaks sphinx_click)
      - python -m pip install "sphinx>=4.0,<8.2"
      # Install supy from PyPI wheel (version from provenance metadata)
      - |
        SUPY_VER=$(python3 -c "
        import json, pathlib
        data = json.loads(pathlib.Path('docs/.docs-source.json').read_text())
        tag = data.get('source_tag', '')
        print(tag if tag else 'supy')
        ")
        echo "Installing supy version: $SUPY_VER"
        if [ "$SUPY_VER" != "supy" ] && [ -n "$SUPY_VER" ]; then
          python -m pip install "supy[dev]==$SUPY_VER" || python -m pip install "supy[dev]"
        else
          python -m pip install "supy[dev]"
        fi
    post_install:
      # Generate RST files after package is installed (data model docs)
      - cd docs && make generate-rst

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Build documentation formats
# Only HTML format (no PDF or ePub to avoid compatibility issues)
formats: []
