# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_install:
      # Fetch all tags for proper version detection
      - git fetch --unshallow || true
      - git fetch --tags || true
      - git update-index --assume-unchanged env.yml docs/source/conf.py
      - make dev
    # pre_build:
    #  - python docs/source/related-softwares/supy/proc_var_info/gen_rst.py

conda:
  environment: env.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation formats
# Only HTML format (no PDF or ePub to avoid compatibility issues)
formats: []

# install the package in the docs/ directory
python:
  install:
    - method: pip
      path: .