# Example: Output configuration with all available groups
# This example shows how to save all available output groups

model:
  control:
    tstep: 300  # 5-minute timestep
    forcing_file: "forcing_2020.txt"
    
    # Save all available output groups
    output_file:
      format: txt       # Traditional text files
      freq: 3600        # Hourly output
      groups:           # All available output groups
        - SUEWS         # Main SUEWS output (energy balance, water balance, etc.)
        - DailyState    # Daily summary variables (only written at end of each day)
        - ESTM          # Element Surface Temperature Method output
        - RSL           # Roughness SubLayer model output
        - BL            # Boundary Layer output
        - snow          # Snow-related output
        - debug         # Debug output (if debug mode is enabled)
      
      # Note: DailyState files will have no frequency suffix in the filename
      # (e.g., London_KCL_2020_DailyState.txt) as they contain daily-only data
      
  physics:
    netradiationmethod: 3
    emissionsmethod: 2
    snowuse: 1  # Enable snow model to get snow output

sites:
  - name: "Urban_Site"
    latitude: 51.5
    longitude: -0.1
    # ... other site parameters