"""Immutable on-disk snapshots for data-interface artefacts."""

from __future__ import annotations

from collections.abc import Mapping
import json
from pathlib import Path, PurePosixPath
from typing import Any

from .canonical import canonical_json_bytes, sha256_digest
from .version import (
    InterfaceKind,
    current_interface_version,
    interface_version_record,
    interface_version_registry,
    validate_interface_version,
)

ARTEFACT_ROOT = Path(__file__).with_name("artefacts")
_EXPECTED_ARTEFACTS: frozenset[str] = frozenset({
    "catalogue.json",
    "schema.json",
})


class SnapshotConflictError(RuntimeError):
    """Raised when existing versioned bytes differ from regenerated bytes."""


class SnapshotVerificationError(RuntimeError):
    """Raised when a stored snapshot is missing, changed or malformed."""


def _safe_relative_name(name: str) -> PurePosixPath:
    path = PurePosixPath(name)
    if (
        not name
        or path.is_absolute()
        or "\\" in name
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise ValueError(f"unsafe artefact path: {name!r}")
    if path.name == "manifest.json":
        raise ValueError("'manifest.json' is reserved for snapshot metadata")
    return path


def _serialise_artefacts(artefacts: Mapping[str, Any]) -> dict[str, bytes]:
    if not artefacts:
        raise ValueError("an interface snapshot must contain at least one artefact")
    if set(artefacts) != _EXPECTED_ARTEFACTS:
        raise ValueError(
            "an interface snapshot must contain exactly catalogue.json and schema.json"
        )

    serialised: dict[str, bytes] = {}
    for name, value in artefacts.items():
        safe_name = _safe_relative_name(name).as_posix()
        if safe_name in serialised:
            raise ValueError(f"duplicate artefact path: {safe_name!r}")
        serialised[safe_name] = canonical_json_bytes(value)
    return serialised


def _snapshot_payload(
    kind: InterfaceKind,
    version: str,
    artefacts: Mapping[str, bytes],
) -> dict[str, Any]:
    return {
        "format_version": 1,
        "interface": kind,
        "interface_version": version,
        "artefacts": [
            {
                "path": name,
                "bytes": len(content),
                "digest": sha256_digest(content),
            }
            for name, content in sorted(artefacts.items())
        ],
    }


def _snapshot_content(
    kind: InterfaceKind,
    version: str,
    artefacts: Mapping[str, Any],
) -> tuple[dict[str, bytes], bytes]:
    if kind not in {"forcing", "output"}:
        raise ValueError(f"unknown data-interface kind: {kind!r}")
    validate_interface_version(version)
    serialised = _serialise_artefacts(artefacts)
    manifest = canonical_json_bytes(_snapshot_payload(kind, version, serialised))
    return serialised, manifest


def snapshot_manifest_digest(
    kind: InterfaceKind,
    version: str,
    artefacts: Mapping[str, Any],
) -> str:
    """Return the digest to bind into an ``InterfaceVersionRecord``."""
    _, manifest = _snapshot_content(kind, version, artefacts)
    return sha256_digest(manifest)


def _check_existing(path: Path, expected: bytes) -> None:
    if path.exists() and path.read_bytes() != expected:
        raise SnapshotConflictError(
            f"refusing to replace immutable data-interface artefact: {path}"
        )


def _write_registered_snapshot(
    root: Path,
    kind: InterfaceKind,
    version: str,
    artefacts: Mapping[str, Any],
) -> Path:
    record = interface_version_record(kind, version)
    serialised, manifest_content = _snapshot_content(kind, version, artefacts)
    digest = sha256_digest(manifest_content)
    if record.manifest_digest != digest:
        raise SnapshotConflictError(
            f"{kind} {version} manifest digest {digest} does not match its "
            f"registered digest {record.manifest_digest}"
        )

    snapshot_dir = Path(root) / kind / version
    targets = {snapshot_dir / name: content for name, content in serialised.items()}
    manifest_path = snapshot_dir / "manifest.json"
    targets[manifest_path] = manifest_content

    # Pre-flight every path before writing so a conflict cannot leave a
    # partially updated snapshot.
    for path, content in targets.items():
        _check_existing(path, content)

    for path, content in targets.items():
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)

    return manifest_path


def write_current_snapshot(
    kind: InterfaceKind,
    artefacts: Mapping[str, Any],
    root: Path = ARTEFACT_ROOT,
) -> Path:
    """Write the registered current version beneath the canonical root.

    ``root`` exists for build staging and tests. Production callers should use
    the package default so repository and wheel snapshots share one layout.
    """
    version = current_interface_version(kind)
    if version is None:
        raise ValueError(f"{kind} has no registered public interface version")
    return _write_registered_snapshot(root, kind, version, artefacts)


def _present_artefacts(manifest_path: Path) -> set[str]:
    return {
        path.relative_to(manifest_path.parent).as_posix()
        for path in manifest_path.parent.rglob("*")
        if path.is_file() and path != manifest_path
    }


def _load_manifest(manifest_path: Path) -> tuple[bytes, dict[str, Any]]:
    try:
        manifest_content = manifest_path.read_bytes()
        payload = json.loads(manifest_content)
    except (FileNotFoundError, json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise SnapshotVerificationError(
            f"cannot read snapshot manifest: {manifest_path}"
        ) from exc

    if not isinstance(payload, dict):
        raise SnapshotVerificationError(
            f"snapshot manifest is not a JSON object: {manifest_path}"
        )
    if canonical_json_bytes(payload) != manifest_content:
        raise SnapshotVerificationError(
            f"snapshot manifest is not canonical JSON: {manifest_path}"
        )
    if payload.get("format_version") != 1:
        raise SnapshotVerificationError(
            f"unsupported snapshot manifest format in {manifest_path}"
        )
    return manifest_content, payload


def verify_snapshot(manifest_path: Path) -> None:
    """Verify identity, canonical bytes and every recorded artefact."""
    manifest_path = Path(manifest_path)
    manifest_content, payload = _load_manifest(manifest_path)

    kind = payload.get("interface")
    version = payload.get("interface_version")
    if kind not in {"forcing", "output"} or not isinstance(version, str):
        raise SnapshotVerificationError(
            f"snapshot manifest has invalid interface identity: {manifest_path}"
        )
    try:
        validate_interface_version(version)
    except ValueError as exc:
        raise SnapshotVerificationError(
            f"snapshot manifest has invalid interface version: {manifest_path}"
        ) from exc
    if (
        manifest_path.name != "manifest.json"
        or manifest_path.parent.name != version
        or manifest_path.parent.parent.name != kind
    ):
        raise SnapshotVerificationError(
            f"snapshot identity does not match its path: {manifest_path}"
        )

    try:
        record = interface_version_record(kind, version)
    except ValueError as exc:
        raise SnapshotVerificationError(
            f"snapshot version is not registered: {kind} {version}"
        ) from exc
    if sha256_digest(manifest_content) != record.manifest_digest:
        raise SnapshotVerificationError(
            f"snapshot manifest does not match its registered digest: {manifest_path}"
        )

    entries = payload.get("artefacts")
    if not isinstance(entries, list):
        raise SnapshotVerificationError(
            f"snapshot manifest has no artefact list: {manifest_path}"
        )

    declared: set[str] = set()
    for entry in entries:
        try:
            name = _safe_relative_name(entry["path"])
            expected_size = entry["bytes"]
            expected_digest = entry["digest"]
        except (KeyError, TypeError, ValueError) as exc:
            raise SnapshotVerificationError(
                f"malformed snapshot entry in {manifest_path}"
            ) from exc

        relative_name = name.as_posix()
        if relative_name in declared:
            raise SnapshotVerificationError(
                f"duplicate snapshot entry {relative_name!r} in {manifest_path}"
            )
        declared.add(relative_name)

        path = manifest_path.parent / name
        try:
            content = path.read_bytes()
        except FileNotFoundError as exc:
            raise SnapshotVerificationError(
                f"snapshot artefact is missing: {path}"
            ) from exc
        if len(content) != expected_size or sha256_digest(content) != expected_digest:
            raise SnapshotVerificationError(
                f"snapshot artefact does not match its manifest: {path}"
            )

    present = _present_artefacts(manifest_path)
    if present != declared:
        raise SnapshotVerificationError(
            f"snapshot contains undeclared or missing artefacts: {manifest_path}"
        )
    if declared != _EXPECTED_ARTEFACTS:
        raise SnapshotVerificationError(
            "snapshot must contain exactly catalogue.json and schema.json: "
            f"{manifest_path}"
        )


def verify_all_snapshots(root: Path = ARTEFACT_ROOT) -> None:
    """Verify all registered snapshots and reject unregistered version dirs."""
    root = Path(root)
    for kind in ("forcing", "output"):
        records = interface_version_registry(kind)
        expected = {record.version for record in records}
        kind_root = root / kind
        present = (
            {path.name for path in kind_root.iterdir() if path.is_dir()}
            if kind_root.exists()
            else set()
        )
        if present != expected:
            raise SnapshotVerificationError(
                f"{kind} snapshot directories {sorted(present)} do not match "
                f"registered versions {sorted(expected)}"
            )
        for version in sorted(expected):
            verify_snapshot(kind_root / version / "manifest.json")
