"""The committed short-sample fixture must stay derived from the shipped sample.

``test/fixtures/sample_short/`` holds a one-month carve of the shipped sample
data so lifecycle tests can build a working simulation without parsing a year
of forcing. Both artefacts are generated by ``make_sample_short.py``; this
module regenerates them from the *installed* sample and fails if the committed
files have drifted, so the shortcut cannot silently stop representing the
sample it was carved from.
"""

import sys
from pathlib import Path

import pytest

from supy.suews_sim import SUEWSSimulation

pytestmark = pytest.mark.api

FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "sample_short"
sys.path.insert(0, str(FIXTURE_DIR))

import make_sample_short  # noqa: E402  (needs the path insert above)

# January 2012, hourly and end-of-interval stamped: 744 rows plus the header.
HOURS_IN_JANUARY = 744
TIMESTEPS_PER_DAY = 288
DAYS_IN_JANUARY = 31


@pytest.mark.parametrize(
    "name", [make_sample_short.FORCING_NAME, make_sample_short.CONFIG_NAME]
)
def test_committed_fixture_matches_generator(name):
    """Each committed artefact is byte-identical to a fresh regeneration."""
    expected = make_sample_short.build()[name]
    actual = (FIXTURE_DIR / name).read_text(encoding="utf-8")

    assert actual == expected, (
        f"{name} has drifted from the shipped sample data. Regenerate with "
        f"`python test/fixtures/sample_short/make_sample_short.py` and commit "
        f"the result."
    )


def test_short_forcing_covers_exactly_january():
    """The carved forcing is January 2012 to the hour, no more and no less."""
    text = (FIXTURE_DIR / make_sample_short.FORCING_NAME).read_text(encoding="utf-8")
    lines = text.splitlines()
    rows = lines[1:]

    assert len(rows) == HOURS_IN_JANUARY
    assert rows[0].split()[:3] == ["2012", "1", "1"]
    # End-of-interval stamping puts the final row at midnight on 1 February.
    assert rows[-1].split()[:3] == ["2012", "32", "0"]


def test_short_config_period_matches_its_forcing(short_sample_yaml_path):
    """The short config asks for exactly the period its forcing supplies.

    This is what makes the fixture safe: a test that asks for more than
    January cannot quietly run on truncated data, because the configured
    period and the loaded forcing end at the same instant.
    """
    sim = SUEWSSimulation(str(short_sample_yaml_path))

    assert len(sim.forcing.df) == TIMESTEPS_PER_DAY * DAYS_IN_JANUARY
    assert str(sim.config.model.control.end_time) == "2012-01-31"
    # end_time is date-only, so it covers the whole day: the last required row
    # is the following midnight, which is the forcing's last row.
    assert sim.forcing.df.index[-1].isoformat() == "2012-02-01T00:00:00"


def test_period_beyond_the_short_sample_is_refused(short_sample_sim):
    """Asking past January fails loudly rather than running on what is there."""
    sim = short_sample_sim()

    with pytest.raises(ValueError, match="does not cover"):
        sim.run(end_date="2012-03-01")
