#!/usr/bin/env python3
"""Generate the Fortran module dependency edges for ``src/suews/Makefile``.

gfortran must compile the file that defines a module before any file that
``USE``s it, because the ``.mod`` file is only written when the defining file
is compiled. The SUEWS Makefile builds each object from its own source and,
without these edges, only gets the order right when ``make`` runs serially
and walks the object lists in the order they are written. With ``make -j``
(gh#1790) objects start in parallel and fail with "Cannot open module file".

This script scans every object the Makefile builds -- the SUEWS sources under
``src/suews/src`` and the SPARTACUS sources named in the Makefile -- for
``MODULE`` and ``USE`` statements and writes one ``<object>: <object>`` edge
per dependency to ``src/suews/Makefile.deps``, which the Makefile includes.

Run it after adding a ``USE`` statement or a source file:

    python scripts/suews/gen_fortran_deps.py

``--check`` exits non-zero when the committed file is out of date;
``test/core/test_fortran_deps.py`` runs it so a stale file fails the tests.

Stdlib-only so it runs anywhere the Makefile does.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

REPO_ROOT = Path(__file__).resolve().parents[2]
SUEWS_DIR = REPO_ROOT / "src" / "suews"
DEPS_FILE = SUEWS_DIR / "Makefile.deps"
SPARTACUS_DIR = SUEWS_DIR / "ext_lib" / "spartacus-surface"
SPARTACUS_SUBDIRS = ("utilities", "radtool", "radsurf")
# Written by the Makefile at build time and not tracked by git, so it may be
# absent when this script runs; its modules are declared here instead.
GENERATED_SOURCES = {
    "src/suews_ctrl_ver.f95": {"module_ctrl_version", "version"},
}

# ``MODULE name`` but not ``MODULE PROCEDURE`` / ``MODULE FUNCTION`` etc.
MODULE_RE = re.compile(
    r"^\s*module\s+(?!procedure\b|function\b|subroutine\b)(\w+)\s*(?:!.*)?$",
    re.IGNORECASE,
)
# ``USE name``, ``USE name, ONLY: ...``, ``USE :: name`` and
# ``USE, NON_INTRINSIC :: name``. Intrinsic modules
# (``USE, INTRINSIC :: iso_c_binding``) do not match and need no edge.
USE_RE = re.compile(
    r"^\s*use\b\s*(?:,\s*non_intrinsic\s*)?(?:::)?\s*(\w+)", re.IGNORECASE
)
SPARTACUS_SOURCE_RE = re.compile(r"\b(\w+)\.F90\b")

HEADER = """\
# Fortran module dependency edges for parallel make (gh#1790).
# Generated by scripts/suews/gen_fortran_deps.py -- do not edit by hand.
# Regenerate after adding a USE statement or a source file:
#     python scripts/suews/gen_fortran_deps.py
"""


def spartacus_sources(makefile_text: str) -> list[Path]:
    """Return the SPARTACUS sources the Makefile compiles into libspartacus.

    Only files named in the Makefile are scanned: the SPARTACUS tree also holds
    sources the SUEWS build never compiles (``easy_netcdf.F90`` needs NetCDF),
    and an edge to one of them would make ``make`` try to build it.
    """
    sources = []
    for name in sorted(set(SPARTACUS_SOURCE_RE.findall(makefile_text))):
        matches = [
            SPARTACUS_DIR / sub / f"{name}.F90"
            for sub in SPARTACUS_SUBDIRS
            if (SPARTACUS_DIR / sub / f"{name}.F90").exists()
        ]
        if len(matches) != 1:
            raise SystemExit(
                f"expected exactly one SPARTACUS source for {name}.F90, "
                f"found {len(matches)}"
            )
        sources.append(matches[0])
    return sources


def object_for(source: Path) -> str:
    """Object path as the Makefile names it, relative to ``src/suews``."""
    return source.relative_to(SUEWS_DIR).with_suffix(".o").as_posix()


def scan(source: Path) -> tuple[set[str], set[str]]:
    """Return the modules a source defines and the modules it uses."""
    defined: set[str] = set()
    used: set[str] = set()
    for line in source.read_text(encoding="utf-8", errors="replace").splitlines():
        if match := MODULE_RE.match(line):
            defined.add(match.group(1).lower())
        elif match := USE_RE.match(line):
            used.add(match.group(1).lower())
    return defined, used


def build_edges(sources: list[Path]) -> dict[str, set[str]]:
    """Map each object to the objects whose modules it uses."""
    scanned = {
        source: scan(source)
        for source in sources
        if source.relative_to(SUEWS_DIR).as_posix() not in GENERATED_SOURCES
    }
    for rel, modules in GENERATED_SOURCES.items():
        scanned[SUEWS_DIR / rel] = (set(modules), set())

    owner: dict[str, str] = {}
    for source, (defined, _) in scanned.items():
        for module in defined:
            if module in owner:
                raise SystemExit(
                    f"module {module} is defined in both {owner[module]} "
                    f"and {object_for(source)}"
                )
            owner[module] = object_for(source)

    edges: dict[str, set[str]] = {}
    for source, (_, used) in scanned.items():
        obj = object_for(source)
        # Modules defined outside the build (WRF-only code paths, intrinsic
        # modules) have no owner here and need no edge.
        deps = {owner[m] for m in used if m in owner and owner[m] != obj}
        if deps:
            edges[obj] = deps
    return edges


def render(edges: dict[str, set[str]]) -> str:
    """Format the edges as Makefile rules, sorted for a stable diff."""
    lines = [HEADER]
    for obj in sorted(edges):
        lines.append(f"{obj}: {' '.join(sorted(edges[obj]))}")
    return "\n".join(lines) + "\n"


def generate() -> str:
    """Return the ``Makefile.deps`` content for the current source tree."""
    makefile_text = (SUEWS_DIR / "Makefile").read_text(encoding="utf-8")
    sources = sorted((SUEWS_DIR / "src").glob("*.f95"))
    sources += spartacus_sources(makefile_text)
    return render(build_edges(sources))


def main(argv: list[str] | None = None) -> int:
    """Write ``Makefile.deps``, or with ``--check`` report whether it is stale."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed Makefile.deps is out of date",
    )
    args = parser.parse_args(argv)

    content = generate()
    if args.check:
        current = DEPS_FILE.read_text(encoding="utf-8") if DEPS_FILE.exists() else ""
        if current != content:
            print(
                f"[X] {DEPS_FILE.relative_to(REPO_ROOT).as_posix()} is out of date; "
                "run: python scripts/suews/gen_fortran_deps.py"
            )
            return 1
        print("[OK] Fortran module dependencies are up to date")
        return 0

    DEPS_FILE.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {DEPS_FILE.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
