[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "suews-mcp"
version = "1.0.0"
description = "SUEWS MCP server"
authors = [{name = "Ting Sun", email = "ting.sun@ucl.ac.uk"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "supy>=2025.10.15",
    "mcp>=0.9.0",
]

[project.scripts]
suews-mcp = "suews_mcp.server:main"

[project.urls]
Homepage = "https://suews.readthedocs.io"
Repository = "https://github.com/UMEP-dev/SUEWS"
Documentation = "https://suews.readthedocs.io/en/latest/mcp-integration.html"
