"""
Static variable metadata for the SUEWS Fortran interface.

Generated from f90wrap docstrings. These lists define the variable
names, intents, and types for the suews_cal_multitsteps interface.

This file replaces the dynamic extraction that previously occurred
at import time via f90wrap-generated docstrings.
"""

import pandas as pd


list_var_input = [
    "ah_min",
    "ah_slope_cooling",
    "ah_slope_heating",
    "ahprof_24hr",
    "air_ext_lw",
    "air_ext_sw",
    "air_ssa_lw",
    "air_ssa_sw",
    "alb",
    "alb_roof",
    "alb_wall",
    "albdectr_id",
    "albevetr_id",
    "albgrass_id",
    "albmax_dectr",
    "albmax_evetr",
    "albmax_grass",
    "albmin_dectr",
    "albmin_evetr",
    "albmin_grass",
    "alpha_bioco2",
    "alpha_enh_bioco2",
    "alt",
    "applianceprofile",
    "baset",
    "baset_cooling",
    "baset_heating",
    "basete",
    "beta_bioco2",
    "beta_enh_bioco2",
    "bldgh",
    "building_frac",
    "building_scale",
    "buildingcount",
    "buildingname",
    "buildingtype",
    "capmax_dec",
    "capmin_dec",
    "chanohm",
    "co2pointsource",
    "coolingsetpointtemperature",
    "coolingsystemcop",
    "cp_roof",
    "cp_surf",
    "cp_wall",
    "cpanohm",
    "crwmax",
    "crwmin",
    "daywat",
    "daywatper",
    "decidcap_id",
    "dectreeh",
    "deepsoiltemperature",
    "dhwdensity",
    "dhwspecificheatcapacity",
    "dhwsurfacearea",
    "dhwvesseldensity",
    "dhwvesselexternalwallconvectioncoefficient",
    "dhwvesselinternalwallconvectioncoefficient",
    "dhwvesselspecificheatcapacity",
    "dhwvesselwallconductivity",
    "dhwvesselwallemissivity",
    "dhwvesselwallthickness",
    "dhwwatervolume",
    "diagnose",
    "dqndt",
    "dqndt_surf",
    "dqnsdt",
    "drainrt",
    "dt_since_start",
    "dz_roof",
    "dz_surf",
    "dz_wall",
    "ef_umolco2perj",
    "emis",
    "emis_roof",
    "emis_wall",
    "emissionsmethod",
    "enddls",
    "enef_v_jkm",
    "evetreeh",
    "externalgroundconductivity",
    "faibldg",
    "faidectree",
    "faievetree",
    "faimethod",
    "faut",
    "fcef_v_kgkm",
    "flag_test",
    "floorinternalconvectioncoefficient",
    "floorthickness",
    "flowchange",
    "footprintarea",
    "frfossilfuel_heat",
    "frfossilfuel_nonheat",
    "g_k",
    "g_max",
    "g_q_base",
    "g_q_shape",
    "g_sm",
    "g_t",
    "gdd_id",
    "gddfull",
    "gridiv",
    "ground_albedo_dir_mult_fact",
    "grounddepth",
    "groundfloorcp",
    "groundfloordensity",
    "groundflooreffectiveconductivity",
    "gsmodel",
    "h_maintain",
    "h_std",
    "hdd_id",
    "heatingsetpointtemperature",
    "heatingsystemefficiency",
    "height",
    "hotwaterflowprofile",
    "hotwaterflowrate",
    "hotwaterheatingefficiency",
    "hotwaterheatingsetpointtemperature",
    "hotwatertankbuildingwallviewfactor",
    "hotwatertankexternalwallconvectioncoefficient",
    "hotwatertankinternalmassviewfactor",
    "hotwatertankinternalwallconvectioncoefficient",
    "hotwatertankspecificheatcapacity",
    "hotwatertankwallconductivity",
    "hotwatertankwalldensity",
    "hotwatertankwallemissivity",
    "humactivity_24hr",
    "icefrac",
    "ie_a",
    "ie_end",
    "ie_m",
    "ie_start",
    "initialindoortemperature",
    "initialoutdoortemperature",
    "internalmassconvectioncoefficient",
    "internalmasscp",
    "internalmassdensity",
    "internalmassemissivity",
    "internalwateruse_h",
    "irrfracbldgs",
    "irrfracbsoil",
    "irrfracdectr",
    "irrfracevetr",
    "irrfracgrass",
    "irrfracpaved",
    "irrfracwater",
    "k_roof",
    "k_surf",
    "k_wall",
    "kkanohm",
    "kmax",
    "lai_id",
    "laimax",
    "laimin",
    "laipower",
    "laitype",
    "lambda_c",
    "lat",
    "latentsensibleratio",
    "len_sim",
    "lenday_id",
    "lng",
    "mainswatertemperature",
    "maxconductance",
    "maxcoolingpower",
    "maxfcmetab",
    "maxheatingpower",
    "maximumhotwaterheatingpower",
    "maximumvolumeofdhwinuse",
    "maxqfmetab",
    "metabolismprofile",
    "metabolismthreshold",
    "metforcingblock",
    "min_res_bioco2",
    "minfcmetab",
    "minimumvolumeofdhwinuse",
    "minqfmetab",
    "n_buildings",
    "n_stream_lw_urban",
    "n_stream_sw_urban",
    "n_vegetation_region_urban",
    "narp_emis_snow",
    "narp_trans_site",
    "netradiationmethod",
    "nlayer",
    "occupants",
    "ohm_coef",
    "ohm_threshsw",
    "ohm_threshwd",
    "ohmincqf",
    "pipecapacity",
    "popdensdaytime",
    "popdensnighttime",
    "popprof_24hr",
    "pormax_dec",
    "pormin_dec",
    "porosity_id",
    "preciplimit",
    "preciplimitalb",
    "qf0_beu",
    "qf_a",
    "qf_b",
    "qf_c",
    "qn_av",
    "qn_s_av",
    "qn_surfs",
    "radmeltfact",
    "raincover",
    "rainmaxres",
    "ratiointernalvolume",
    "rcmethod",
    "resp_a",
    "resp_b",
    "roof_albedo_dir_mult_fact",
    "roofabsorbtivity",
    "roofcp",
    "roofdensity",
    "roofeffectiveconductivity",
    "roofextcp",
    "roofextdensity",
    "roofexteffectiveconductivity",
    "roofexternalconvectioncoefficient",
    "roofexternalemissivity",
    "roofextthickness",
    "roofinternalconvectioncoefficient",
    "roofinternalemissivity",
    "roofoutercapfrac",
    "roofreflectivity",
    "roofthickness",
    "rooftransmissivity",
    "roughlenheatmethod",
    "roughlenmommethod",
    "rsllevel",
    "rslmethod",
    "runofftowater",
    "s1",
    "s2",
    "sathydraulicconduct",
    "sdd_id",
    "sddfull",
    "sfr_surf",
    "smdmethod",
    "snowalb",
    "snowalbmax",
    "snowalbmin",
    "snowdens",
    "snowdensmax",
    "snowdensmin",
    "snowfallcum",
    "snowfrac",
    "snowlimbldg",
    "snowlimpaved",
    "snowpack",
    "snowpacklimit",
    "snowprof_24hr",
    "snowuse",
    "snowwater",
    "soildepth",
    "soilstore_roof",
    "soilstore_surf",
    "soilstore_wall",
    "soilstorecap_roof",
    "soilstorecap_surf",
    "soilstorecap_wall",
    "stabilitymethod",
    "startdls",
    "state_roof",
    "state_surf",
    "state_wall",
    "statelimit_roof",
    "statelimit_surf",
    "statelimit_wall",
    "stebbs_height",
    "stebbsmethod",
    "storageheatmethod",
    "storedrainprm",
    "surfacearea",
    "sw_dn_direct_frac",
    "tair_av",
    "tau_a",
    "tau_f",
    "tau_r",
    "temp_roof",
    "temp_surf",
    "temp_wall",
    "tempmeltfact",
    "th",
    "theta_bioco2",
    "timezone",
    "tin_roof",
    "tin_surf",
    "tin_wall",
    "tl",
    "tmax_id",
    "tmin_id",
    "trafficrate",
    "trafficunits",
    "traffprof_24hr",
    "ts5mindata_ir",
    "tsfc_roof",
    "tsfc_surf",
    "tsfc_wall",
    "tstep",
    "tstep_prev",
    "use_sw_direct_albedo",
    "veg_contact_fraction_const",
    "veg_frac",
    "veg_fsd_const",
    "veg_scale",
    "veg_ssa_lw",
    "veg_ssa_sw",
    "veg_type",
    "ventilationrate",
    "wall_specular_frac",
    "wallabsorbtivity",
    "wallcp",
    "walldensity",
    "walleffectiveconductivity",
    "wallextcp",
    "wallextdensity",
    "wallexteffectiveconductivity",
    "wallexternalarea",
    "wallexternalconvectioncoefficient",
    "wallexternalemissivity",
    "wallextthickness",
    "wallinternalconvectioncoefficient",
    "wallinternalemissivity",
    "walloutercapfrac",
    "wallreflectivity",
    "wallthickness",
    "walltransmissivity",
    "waterdist",
    "watertanksurfacearea",
    "watertankwallthickness",
    "watertankwatervolume",
    "waterusemethod",
    "wetthresh_roof",
    "wetthresh_surf",
    "wetthresh_wall",
    "windowabsorbtivity",
    "windowcp",
    "windowdensity",
    "windoweffectiveconductivity",
    "windowexternalconvectioncoefficient",
    "windowexternalemissivity",
    "windowinternalconvectioncoefficient",
    "windowinternalemissivity",
    "windowreflectivity",
    "windowthickness",
    "windowtransmissivity",
    "wuday_id",
    "wuprofa_24hr",
    "wuprofm_24hr",
    "wwr",
    "z",
    "z0m_in",
    "zdm_in",
]


list_var_inout = [
    "alb",
    "albdectr_id",
    "albevetr_id",
    "albgrass_id",
    "decidcap_id",
    "diagnose",
    "dqndt",
    "dqndt_surf",
    "dqnsdt",
    "gdd_id",
    "hdd_id",
    "icefrac",
    "lai_id",
    "lenday_id",
    "porosity_id",
    "qn_av",
    "qn_s_av",
    "qn_surfs",
    "sdd_id",
    "snowalb",
    "snowdens",
    "snowfallcum",
    "snowfrac",
    "snowpack",
    "snowwater",
    "soilstore_roof",
    "soilstore_surf",
    "soilstore_wall",
    "state_roof",
    "state_surf",
    "state_wall",
    "storedrainprm",
    "tair_av",
    "temp_roof",
    "temp_surf",
    "temp_wall",
    "tmax_id",
    "tmin_id",
    "tsfc_roof",
    "tsfc_surf",
    "tsfc_wall",
    "wuday_id",
]


list_var_output = []


set_var_input = set(list_var_input)
set_var_inout = set(list_var_inout)
set_var_ouput = set(list_var_output)


list_var_input_multitsteps = [
    "ah_min",
    "ah_slope_cooling",
    "ah_slope_heating",
    "ahprof_24hr",
    "air_ext_lw",
    "air_ext_sw",
    "air_ssa_lw",
    "air_ssa_sw",
    "alb",
    "alb_roof",
    "alb_wall",
    "albdectr_id",
    "albevetr_id",
    "albgrass_id",
    "albmax_dectr",
    "albmax_evetr",
    "albmax_grass",
    "albmin_dectr",
    "albmin_evetr",
    "albmin_grass",
    "alpha_bioco2",
    "alpha_enh_bioco2",
    "alt",
    "applianceprofile",
    "baset",
    "baset_cooling",
    "baset_heating",
    "basete",
    "beta_bioco2",
    "beta_enh_bioco2",
    "bldgh",
    "building_frac",
    "building_scale",
    "buildingcount",
    "buildingname",
    "buildingtype",
    "capmax_dec",
    "capmin_dec",
    "chanohm",
    "co2pointsource",
    "coolingsetpointtemperature",
    "coolingsystemcop",
    "cp_roof",
    "cp_surf",
    "cp_wall",
    "cpanohm",
    "crwmax",
    "crwmin",
    "daywat",
    "daywatper",
    "decidcap_id",
    "dectreeh",
    "deepsoiltemperature",
    "dhwdensity",
    "dhwspecificheatcapacity",
    "dhwsurfacearea",
    "dhwvesseldensity",
    "dhwvesselexternalwallconvectioncoefficient",
    "dhwvesselinternalwallconvectioncoefficient",
    "dhwvesselspecificheatcapacity",
    "dhwvesselwallconductivity",
    "dhwvesselwallemissivity",
    "dhwvesselwallthickness",
    "dhwwatervolume",
    "diagnose",
    "dqndt",
    "dqndt_surf",
    "dqnsdt",
    "drainrt",
    "dt_since_start",
    "dz_roof",
    "dz_surf",
    "dz_wall",
    "ef_umolco2perj",
    "emis",
    "emis_roof",
    "emis_wall",
    "emissionsmethod",
    "enddls",
    "enef_v_jkm",
    "evetreeh",
    "externalgroundconductivity",
    "faibldg",
    "faidectree",
    "faievetree",
    "faimethod",
    "faut",
    "fcef_v_kgkm",
    "flag_test",
    "floorinternalconvectioncoefficient",
    "floorthickness",
    "flowchange",
    "footprintarea",
    "frfossilfuel_heat",
    "frfossilfuel_nonheat",
    "g_k",
    "g_max",
    "g_q_base",
    "g_q_shape",
    "g_sm",
    "g_t",
    "gdd_id",
    "gddfull",
    "gridiv",
    "ground_albedo_dir_mult_fact",
    "grounddepth",
    "groundfloorcp",
    "groundfloordensity",
    "groundflooreffectiveconductivity",
    "gsmodel",
    "h_maintain",
    "h_std",
    "hdd_id",
    "heatingsetpointtemperature",
    "heatingsystemefficiency",
    "height",
    "hotwaterflowprofile",
    "hotwaterflowrate",
    "hotwaterheatingefficiency",
    "hotwaterheatingsetpointtemperature",
    "hotwatertankbuildingwallviewfactor",
    "hotwatertankexternalwallconvectioncoefficient",
    "hotwatertankinternalmassviewfactor",
    "hotwatertankinternalwallconvectioncoefficient",
    "hotwatertankspecificheatcapacity",
    "hotwatertankwallconductivity",
    "hotwatertankwalldensity",
    "hotwatertankwallemissivity",
    "humactivity_24hr",
    "icefrac",
    "ie_a",
    "ie_end",
    "ie_m",
    "ie_start",
    "initialindoortemperature",
    "initialoutdoortemperature",
    "internalmassconvectioncoefficient",
    "internalmasscp",
    "internalmassdensity",
    "internalmassemissivity",
    "internalwateruse_h",
    "irrfracbldgs",
    "irrfracbsoil",
    "irrfracdectr",
    "irrfracevetr",
    "irrfracgrass",
    "irrfracpaved",
    "irrfracwater",
    "k_roof",
    "k_surf",
    "k_wall",
    "kkanohm",
    "kmax",
    "lai_id",
    "laimax",
    "laimin",
    "laipower",
    "laitype",
    "lambda_c",
    "lat",
    "latentsensibleratio",
    "len_sim",
    "lenday_id",
    "lng",
    "mainswatertemperature",
    "maxconductance",
    "maxcoolingpower",
    "maxfcmetab",
    "maxheatingpower",
    "maximumhotwaterheatingpower",
    "maximumvolumeofdhwinuse",
    "maxqfmetab",
    "metabolismprofile",
    "metabolismthreshold",
    "metforcingblock",
    "min_res_bioco2",
    "minfcmetab",
    "minimumvolumeofdhwinuse",
    "minqfmetab",
    "n_buildings",
    "n_stream_lw_urban",
    "n_stream_sw_urban",
    "n_vegetation_region_urban",
    "narp_emis_snow",
    "narp_trans_site",
    "netradiationmethod",
    "nlayer",
    "occupants",
    "ohm_coef",
    "ohm_threshsw",
    "ohm_threshwd",
    "ohmincqf",
    "pipecapacity",
    "popdensdaytime",
    "popdensnighttime",
    "popprof_24hr",
    "pormax_dec",
    "pormin_dec",
    "porosity_id",
    "preciplimit",
    "preciplimitalb",
    "qf0_beu",
    "qf_a",
    "qf_b",
    "qf_c",
    "qn_av",
    "qn_s_av",
    "qn_surfs",
    "radmeltfact",
    "raincover",
    "rainmaxres",
    "ratiointernalvolume",
    "rcmethod",
    "resp_a",
    "resp_b",
    "roof_albedo_dir_mult_fact",
    "roofabsorbtivity",
    "roofcp",
    "roofdensity",
    "roofeffectiveconductivity",
    "roofextcp",
    "roofextdensity",
    "roofexteffectiveconductivity",
    "roofexternalconvectioncoefficient",
    "roofexternalemissivity",
    "roofextthickness",
    "roofinternalconvectioncoefficient",
    "roofinternalemissivity",
    "roofoutercapfrac",
    "roofreflectivity",
    "roofthickness",
    "rooftransmissivity",
    "roughlenheatmethod",
    "roughlenmommethod",
    "rsllevel",
    "rslmethod",
    "runofftowater",
    "s1",
    "s2",
    "sathydraulicconduct",
    "sdd_id",
    "sddfull",
    "sfr_surf",
    "smdmethod",
    "snowalb",
    "snowalbmax",
    "snowalbmin",
    "snowdens",
    "snowdensmax",
    "snowdensmin",
    "snowfallcum",
    "snowfrac",
    "snowlimbldg",
    "snowlimpaved",
    "snowpack",
    "snowpacklimit",
    "snowprof_24hr",
    "snowuse",
    "snowwater",
    "soildepth",
    "soilstore_roof",
    "soilstore_surf",
    "soilstore_wall",
    "soilstorecap_roof",
    "soilstorecap_surf",
    "soilstorecap_wall",
    "stabilitymethod",
    "startdls",
    "state_roof",
    "state_surf",
    "state_wall",
    "statelimit_roof",
    "statelimit_surf",
    "statelimit_wall",
    "stebbs_height",
    "stebbsmethod",
    "storageheatmethod",
    "storedrainprm",
    "surfacearea",
    "sw_dn_direct_frac",
    "tair_av",
    "tau_a",
    "tau_f",
    "tau_r",
    "temp_roof",
    "temp_surf",
    "temp_wall",
    "tempmeltfact",
    "th",
    "theta_bioco2",
    "timezone",
    "tin_roof",
    "tin_surf",
    "tin_wall",
    "tl",
    "tmax_id",
    "tmin_id",
    "trafficrate",
    "trafficunits",
    "traffprof_24hr",
    "ts5mindata_ir",
    "tsfc_roof",
    "tsfc_surf",
    "tsfc_wall",
    "tstep",
    "tstep_prev",
    "use_sw_direct_albedo",
    "veg_contact_fraction_const",
    "veg_frac",
    "veg_fsd_const",
    "veg_scale",
    "veg_ssa_lw",
    "veg_ssa_sw",
    "veg_type",
    "ventilationrate",
    "wall_specular_frac",
    "wallabsorbtivity",
    "wallcp",
    "walldensity",
    "walleffectiveconductivity",
    "wallextcp",
    "wallextdensity",
    "wallexteffectiveconductivity",
    "wallexternalarea",
    "wallexternalconvectioncoefficient",
    "wallexternalemissivity",
    "wallextthickness",
    "wallinternalconvectioncoefficient",
    "wallinternalemissivity",
    "walloutercapfrac",
    "wallreflectivity",
    "wallthickness",
    "walltransmissivity",
    "waterdist",
    "watertanksurfacearea",
    "watertankwallthickness",
    "watertankwatervolume",
    "waterusemethod",
    "wetthresh_roof",
    "wetthresh_surf",
    "wetthresh_wall",
    "windowabsorbtivity",
    "windowcp",
    "windowdensity",
    "windoweffectiveconductivity",
    "windowexternalconvectioncoefficient",
    "windowexternalemissivity",
    "windowinternalconvectioncoefficient",
    "windowinternalemissivity",
    "windowreflectivity",
    "windowthickness",
    "windowtransmissivity",
    "wuday_id",
    "wuprofa_24hr",
    "wuprofm_24hr",
    "wwr",
    "z",
    "z0m_in",
    "zdm_in",
]


list_var_inout_multitsteps = [
    "alb",
    "albdectr_id",
    "albevetr_id",
    "albgrass_id",
    "decidcap_id",
    "diagnose",
    "dqndt",
    "dqndt_surf",
    "dqnsdt",
    "gdd_id",
    "hdd_id",
    "icefrac",
    "lai_id",
    "lenday_id",
    "porosity_id",
    "qn_av",
    "qn_s_av",
    "qn_surfs",
    "sdd_id",
    "snowalb",
    "snowdens",
    "snowfallcum",
    "snowfrac",
    "snowpack",
    "snowwater",
    "soilstore_roof",
    "soilstore_surf",
    "soilstore_wall",
    "state_roof",
    "state_surf",
    "state_wall",
    "storedrainprm",
    "tair_av",
    "temp_roof",
    "temp_surf",
    "temp_wall",
    "tmax_id",
    "tmin_id",
    "tsfc_roof",
    "tsfc_surf",
    "tsfc_wall",
    "wuday_id",
]


list_var_output_multitsteps = []


set_var_input_multitsteps = set(list_var_input_multitsteps)
set_var_inout_multitsteps = set(list_var_inout_multitsteps)
set_var_ouput_multitsteps = set(list_var_output_multitsteps)

# Variables used in df_state validation
set_var_use = set_var_input_multitsteps


# Variable type information (intent, rank, dtype, bounds)
# Used by _run.py to determine integer vs float, scalar vs array
_VAR_INFO_DICT = {
    "ah_min": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "ah_slope_cooling": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "ah_slope_heating": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "ahprof_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n1)"},
    "air_ext_lw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "air_ext_sw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "air_ssa_lw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "air_ssa_sw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "alb": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n2)"},
    "alb_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n38)"},
    "alb_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n40)"},
    "albdectr_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "albevetr_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "albgrass_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "albmax_dectr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "albmax_evetr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "albmax_grass": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "albmin_dectr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "albmin_evetr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "albmin_grass": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "alpha_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n3)"},
    "alpha_enh_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n4)"},
    "alt": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "applianceprofile": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n31)"},
    "baset": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n5)"},
    "baset_cooling": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "baset_heating": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "basete": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n6)"},
    "beta_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n7)"},
    "beta_enh_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n8)"},
    "bldgh": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "block_mod_state": {"intent": "input", "rank": 1, "dtype": "array('i')", "bounds": "(2)"},
    "building_frac": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n34)"},
    "building_scale": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n36)"},
    "buildingcount": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "buildingname": {"intent": "input", "rank": 0, "dtype": "string(len=10)", "bounds": 0},
    "buildingtype": {"intent": "input", "rank": 0, "dtype": "string(len=10)", "bounds": 0},
    "capmax_dec": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "capmin_dec": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "chanohm": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n9)"},
    "co2pointsource": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "coolingsetpointtemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "coolingsystemcop": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "cp_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n86)"},
    "cp_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n87)"},
    "cp_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n85)"},
    "cpanohm": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n10)"},
    "crwmax": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "crwmin": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "daywat": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(7)"},
    "daywatper": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(7)"},
    "decidcap_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "dectreeh": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "deepsoiltemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwspecificheatcapacity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwsurfacearea": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesseldensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselexternalwallconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselinternalwallconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselspecificheatcapacity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselwallconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselwallemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwvesselwallthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dhwwatervolume": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "diagnose": {"intent": "in/output", "rank": 0, "dtype": "array(int,'i')", "bounds": 0},
    "dqndt": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "dqndt_surf": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n11)"},
    "dqnsdt": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "drainrt": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "dt_since_start": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "dz_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n89)"},
    "dz_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n90)"},
    "dz_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n88)"},
    "ef_umolco2perj": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "emis": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n13)"},
    "emis_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n39)"},
    "emis_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n41)"},
    "emissionsmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "enddls": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "enef_v_jkm": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "evetreeh": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "externalgroundconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "faibldg": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "faidectree": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "faievetree": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "faimethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "faut": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "fcef_v_kgkm": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "flag_test": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "floorinternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "floorthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "flowchange": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "footprintarea": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "frfossilfuel_heat": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "frfossilfuel_nonheat": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_k": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_max": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_q_base": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_q_shape": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_sm": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "g_t": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "gdd_id": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n14)"},
    "gddfull": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n15)"},
    "gridiv": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "ground_albedo_dir_mult_fact": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "grounddepth": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "groundfloorcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "groundfloordensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "groundflooreffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "gsmodel": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "h_maintain": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "h_std": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hdd_id": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(12)"},
    "heatingsetpointtemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "heatingsystemefficiency": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "height": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n33)"},
    "hotwaterflowprofile": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n32)"},
    "hotwaterflowrate": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwaterheatingefficiency": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwaterheatingsetpointtemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankbuildingwallviewfactor": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankexternalwallconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankinternalmassviewfactor": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankinternalwallconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankspecificheatcapacity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankwallconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankwalldensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "hotwatertankwallemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "humactivity_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n16)"},
    "icefrac": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n17)"},
    "ie_a": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(3)"},
    "ie_end": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "ie_m": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(3)"},
    "ie_start": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "initialindoortemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "initialoutdoortemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "internalmassconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "internalmasscp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "internalmassdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "internalmassemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "internalwateruse_h": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracbldgs": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracbsoil": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracdectr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracevetr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracgrass": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracpaved": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "irrfracwater": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "k_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n83)"},
    "k_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n84)"},
    "k_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n82)"},
    "kkanohm": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n18)"},
    "kmax": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "lai_id": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n19)"},
    "laimax": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n20)"},
    "laimin": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n21)"},
    "laipower": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n22)"},
    "laitype": {"intent": "input", "rank": 1, "dtype": "array('i')", "bounds": "(n23)"},
    "lambda_c": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "lat": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "latentsensibleratio": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "len_sim": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "lenday_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "lng": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "mainswatertemperature": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maxconductance": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(3)"},
    "maxcoolingpower": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maxfcmetab": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maxheatingpower": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maximumhotwaterheatingpower": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maximumvolumeofdhwinuse": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "maxqfmetab": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "metabolismprofile": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n30)"},
    "metabolismthreshold": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "metforcingblock": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n0)"},
    "min_res_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n25)"},
    "minfcmetab": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "minimumvolumeofdhwinuse": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "minqfmetab": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "n_buildings": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "n_stream_lw_urban": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "n_stream_sw_urban": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "n_vegetation_region_urban": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "narp_emis_snow": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "narp_trans_site": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "netradiationmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "nlayer": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "occupants": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "ohm_coef": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n26)"},
    "ohm_threshsw": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n27)"},
    "ohm_threshwd": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n28)"},
    "ohmincqf": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "pipecapacity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "popdensdaytime": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "popdensnighttime": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "popprof_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n29)"},
    "pormax_dec": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "pormin_dec": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "porosity_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "preciplimit": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "preciplimitalb": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "qf0_beu": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "qf_a": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "qf_b": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "qf_c": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "qn_av": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "qn_s_av": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "qn_surfs": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n12)"},
    "radmeltfact": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "raincover": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "rainmaxres": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "ratiointernalvolume": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "rcmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "resp_a": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n44)"},
    "resp_b": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n45)"},
    "roof_albedo_dir_mult_fact": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n42)"},
    "roofabsorbtivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofeffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofextcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofextdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofexteffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofexternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofexternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofextthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofinternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofinternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofoutercapfrac": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofreflectivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roofthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "rooftransmissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "roughlenheatmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "roughlenmommethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "rsllevel": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "rslmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "runofftowater": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "s1": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "s2": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "sathydraulicconduct": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n46)"},
    "sdd_id": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n48)"},
    "sddfull": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n47)"},
    "sfr_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n72)"},
    "smdmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "snowalb": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "snowalbmax": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowalbmin": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowdens": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n50)"},
    "snowdensmax": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowdensmin": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowfallcum": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "snowfrac": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n51)"},
    "snowlimbldg": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowlimpaved": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "snowpack": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n52)"},
    "snowpacklimit": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n49)"},
    "snowprof_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n53)"},
    "snowuse": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "snowwater": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n24)"},
    "soildepth": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n54)"},
    "soilstore_roof": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n60)"},
    "soilstore_surf": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n55)"},
    "soilstore_wall": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n65)"},
    "soilstorecap_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n61)"},
    "soilstorecap_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n56)"},
    "soilstorecap_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n66)"},
    "stabilitymethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "startdls": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "state_debug": {"intent": "input", "rank": 1, "dtype": "array('i')", "bounds": "(2)"},
    "state_roof": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n62)"},
    "state_surf": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n57)"},
    "state_wall": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n67)"},
    "statelimit_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n63)"},
    "statelimit_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n58)"},
    "statelimit_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n68)"},
    "stebbs_height": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "stebbsmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "storageheatmethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "storedrainprm": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n70)"},
    "surfacearea": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "sw_dn_direct_frac": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "tair_av": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "tau_a": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "tau_f": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "tau_r": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "temp_roof": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n76)"},
    "temp_surf": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n78)"},
    "temp_wall": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n77)"},
    "tempmeltfact": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "th": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "theta_bioco2": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n71)"},
    "timezone": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "tin_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n79)"},
    "tin_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n81)"},
    "tin_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n80)"},
    "tl": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "tmax_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "tmin_id": {"intent": "in/output", "rank": 0, "dtype": "array(float,'d')", "bounds": 0},
    "trafficrate": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(2)"},
    "trafficunits": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "traffprof_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n91)"},
    "ts5mindata_ir": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n92)"},
    "tsfc_roof": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n73)"},
    "tsfc_surf": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n75)"},
    "tsfc_wall": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(n74)"},
    "tstep": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "tstep_prev": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "use_sw_direct_albedo": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "veg_contact_fraction_const": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "veg_frac": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n35)"},
    "veg_fsd_const": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "veg_scale": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n37)"},
    "veg_ssa_lw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "veg_ssa_sw": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "veg_type": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "ventilationrate": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wall_specular_frac": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n43)"},
    "wallabsorbtivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "walldensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "walleffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallextcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallextdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallexteffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallexternalarea": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallexternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallexternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallextthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallinternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallinternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "walloutercapfrac": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallreflectivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wallthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "walltransmissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "waterdist": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n93)"},
    "watertanksurfacearea": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "watertankwallthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "watertankwatervolume": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "waterusemethod": {"intent": "input", "rank": 0, "dtype": "int", "bounds": 0},
    "wetthresh_roof": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n64)"},
    "wetthresh_surf": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n59)"},
    "wetthresh_wall": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n69)"},
    "windowabsorbtivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowcp": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowdensity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windoweffectiveconductivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowexternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowexternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowinternalconvectioncoefficient": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowinternalemissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowreflectivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowthickness": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "windowtransmissivity": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "wuday_id": {"intent": "in/output", "rank": 1, "dtype": "array('d')", "bounds": "(9)"},
    "wuprofa_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n94)"},
    "wuprofm_24hr": {"intent": "input", "rank": 1, "dtype": "array('d')", "bounds": "(n95)"},
    "wwr": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "z": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "z0m_in": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
    "zdm_in": {"intent": "input", "rank": 0, "dtype": "float", "bounds": 0},
}


def get_df_var_info() -> pd.DataFrame:
    """Return variable info as a DataFrame, matching the old df_var_info."""
    df = pd.DataFrame.from_dict(_VAR_INFO_DICT, orient="index")
    df.index.name = "name"
    try:
        df = df.infer_objects()
    except TypeError:
        df = df.infer_objects(copy=False)
    return df
