"""Canonical SUEWS forcing-variable definitions."""

from __future__ import annotations

from .variables import (
    ForcingDataType,
    ForcingRequirement,
    ForcingVariable,
    ForcingVariableRegistry,
    NumericRange,
    PhysicsRequirement,
    TemporalSemantics,
)

MISSING_VALUE = -999.0

ALL_SURFACES = (
    "paved",
    "bldgs",
    "evetr",
    "dectr",
    "grass",
    "bsoil",
    "water",
)
VEGETATED_SURFACES = ("evetr", "dectr", "grass")

_NET_RADIATION_QN = PhysicsRequirement(
    field="net_radiation",
    values=(0,),
    legacy_field="netradiationmethod",
    legacy_values=(0,),
)
_NET_RADIATION_LDOWN = PhysicsRequirement(
    field="net_radiation",
    values=(1, 11, 100, 1001),
    legacy_field="netradiationmethod",
    legacy_values=(1,),
)
_NET_RADIATION_KDOWN_FCLD = PhysicsRequirement(
    field="net_radiation",
    values=(2, 12, 200, 1002),
    legacy_field="netradiationmethod",
    legacy_values=(2,),
)
_NET_RADIATION_KDOWN = PhysicsRequirement(
    field="net_radiation",
    values=(3, 13, 300, 1003),
    legacy_field="netradiationmethod",
    legacy_values=(3,),
)


def _time(name: str, description: str, position: int) -> ForcingVariable:
    return ForcingVariable(
        name=name,
        data_type=ForcingDataType.INTEGER,
        unit="1",
        description=description,
        temporal_semantics=TemporalSemantics.TIME,
        requirement=ForcingRequirement.DATETIME,
        legacy_position=position,
    )


FORCING_VARIABLES = (
    _time("iy", "Calendar year", 1),
    _time("id", "Day of year", 2),
    _time("it", "Hour at the end of the forcing interval", 3),
    _time("imin", "Minute at the end of the forcing interval", 4),
    ForcingVariable(
        name="qn",
        aliases=("net_radiation", "qstar", "q_star"),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Observed net all-wave radiation",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(_NET_RADIATION_QN,),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=-500, maximum=1300),
        legacy_position=5,
    ),
    ForcingVariable(
        name="qh",
        aliases=("sensible_heat", "h"),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Observed turbulent sensible heat flux",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=-500, maximum=1300),
        legacy_position=6,
    ),
    ForcingVariable(
        name="qe",
        aliases=("latent_heat", "le"),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Observed turbulent latent heat flux",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=-500, maximum=1300),
        legacy_position=7,
    ),
    ForcingVariable(
        name="qs",
        aliases=("storage_heat",),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Observed net storage heat flux",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(
            PhysicsRequirement(
                field="storage_heat",
                values=(0,),
                legacy_field="storageheatmethod",
                legacy_values=(0,),
            ),
        ),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=-100, maximum=650),
        legacy_position=8,
    ),
    ForcingVariable(
        name="qf",
        aliases=("anthropogenic_heat",),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Observed anthropogenic heat flux",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(
            PhysicsRequirement(
                field="emissions",
                values=(0,),
                legacy_field="emissionsmethod",
                legacy_values=(0,),
            ),
        ),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=-500, maximum=1300),
        legacy_position=9,
    ),
    ForcingVariable(
        name="U",
        aliases=("wind_speed", "wind", "u"),
        data_type=ForcingDataType.NUMBER,
        unit="m s-1",
        description="Wind speed at the forcing measurement height",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.BASELINE,
        valid_range=NumericRange(minimum=0.01, maximum=60),
        legacy_position=10,
    ),
    ForcingVariable(
        name="RH",
        aliases=("relative_humidity", "humidity", "rh"),
        data_type=ForcingDataType.NUMBER,
        unit="%",
        description="Relative humidity",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.BASELINE,
        valid_range=NumericRange(minimum=0.0001, maximum=105),
        legacy_position=11,
    ),
    ForcingVariable(
        name="Tair",
        aliases=("temperature", "air_temperature", "temp", "t_air", "ta"),
        data_type=ForcingDataType.NUMBER,
        unit="degC",
        description="Air temperature",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.BASELINE,
        valid_range=NumericRange(minimum=-60, maximum=90),
        legacy_position=12,
    ),
    ForcingVariable(
        name="pres",
        aliases=("pressure", "air_pressure", "p"),
        data_type=ForcingDataType.NUMBER,
        unit="kPa",
        description="Air pressure",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.BASELINE,
        valid_range=NumericRange(minimum=68, maximum=130),
        validation_scale=10,
        legacy_position=13,
    ),
    ForcingVariable(
        name="rain",
        aliases=("precipitation", "rainfall", "precip"),
        data_type=ForcingDataType.NUMBER,
        unit="mm",
        description="Precipitation accumulated over the forcing interval",
        temporal_semantics=TemporalSemantics.SUM,
        requirement=ForcingRequirement.BASELINE,
        valid_range=NumericRange(minimum=0),
        legacy_position=14,
    ),
    ForcingVariable(
        name="kdown",
        aliases=("shortwave_down", "solar_radiation", "sw_down", "k_down"),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Incoming short-wave radiation",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.BASELINE,
        physics_requirements=(
            _NET_RADIATION_KDOWN_FCLD,
            _NET_RADIATION_KDOWN,
        ),
        valid_range=NumericRange(minimum=0, maximum=1400),
        legacy_position=15,
    ),
    ForcingVariable(
        name="snow",
        aliases=("snowfall",),
        data_type=ForcingDataType.NUMBER,
        unit="1",
        description="Fraction of precipitation that falls as snow",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=1),
        legacy_position=16,
    ),
    ForcingVariable(
        name="ldown",
        aliases=("longwave_down", "lw_down", "l_down"),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Incoming long-wave radiation",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(_NET_RADIATION_LDOWN,),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=100, maximum=600),
        legacy_position=17,
    ),
    ForcingVariable(
        name="fcld",
        aliases=("cloud_fraction", "cloud_cover", "clouds"),
        data_type=ForcingDataType.NUMBER,
        unit="1",
        description="Cloud fraction",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(_NET_RADIATION_KDOWN_FCLD,),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=1),
        legacy_position=18,
    ),
    ForcingVariable(
        name="Wuh",
        aliases=("water_use", "external_water", "wu_mm"),
        data_type=ForcingDataType.NUMBER,
        unit="mm",
        description="External water use accumulated over the forcing interval",
        temporal_semantics=TemporalSemantics.SUM,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(PhysicsRequirement(field="water_use", values=(1,)),),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=10),
        surface_suffixes=ALL_SURFACES,
        legacy_position=19,
    ),
    ForcingVariable(
        name="xsmd",
        aliases=("soil_moisture", "smd"),
        data_type=ForcingDataType.NUMBER,
        unit="varies with soil moisture deficit method",
        description="Observed soil moisture",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(
            PhysicsRequirement(
                field="soil_moisture_deficit",
                values=(1, 2),
                legacy_field="smdmethod",
                legacy_values=(1, 2),
            ),
        ),
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0),
        legacy_position=20,
    ),
    ForcingVariable(
        name="lai",
        aliases=("leaf_area_index",),
        data_type=ForcingDataType.NUMBER,
        unit="m2 m-2",
        description="Observed leaf area index",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.CONDITIONAL,
        physics_requirements=(
            PhysicsRequirement(
                field="laimethod",
                values=(0,),
                legacy_field="laimethod",
                legacy_values=(0,),
            ),
        ),
        missing_value=MISSING_VALUE,
        surface_suffixes=VEGETATED_SURFACES,
        legacy_position=21,
    ),
    ForcingVariable(
        name="kdiff",
        aliases=("diffuse_radiation",),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Diffuse component of incoming short-wave radiation",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=1000),
        legacy_position=22,
    ),
    ForcingVariable(
        name="kdir",
        aliases=("direct_radiation",),
        data_type=ForcingDataType.NUMBER,
        unit="W m-2",
        description="Direct component of incoming short-wave radiation",
        temporal_semantics=TemporalSemantics.AVERAGE,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=1400),
        legacy_position=23,
    ),
    ForcingVariable(
        name="wdir",
        aliases=("wind_direction", "wd"),
        data_type=ForcingDataType.NUMBER,
        unit="degree",
        description="Wind direction",
        temporal_semantics=TemporalSemantics.INSTANTANEOUS,
        requirement=ForcingRequirement.OPTIONAL,
        missing_value=MISSING_VALUE,
        valid_range=NumericRange(minimum=0, maximum=360),
        legacy_position=24,
    ),
    ForcingVariable(
        name="isec",
        data_type=ForcingDataType.INTEGER,
        unit="s",
        description="Derived second within the minute",
        temporal_semantics=TemporalSemantics.TIME,
        requirement=ForcingRequirement.DERIVED,
        input_column=False,
    ),
)

FORCING_REGISTRY = ForcingVariableRegistry(variables=FORCING_VARIABLES)
