"""Inventory of externally supplied SUEWS forcing variables."""

from .registry import (
    ForcingRegistry,
    ForcingRequiredness,
    ForcingRole,
    ForcingVariable,
    MissingValuePolicy,
    RequirementRule,
    TemporalSemantics,
)


def _variable(
    name: str,
    unit: str | None,
    description: str,
    role: ForcingRole,
    temporal: TemporalSemantics,
    requiredness: ForcingRequiredness,
    missing_policy: MissingValuePolicy,
    **metadata: object,
) -> ForcingVariable:
    """Construct one validated forcing-variable definition."""
    return ForcingVariable(
        name=name,
        data_type="number",
        role=role,
        unit=unit,
        description=description,
        temporal=temporal,
        requiredness=requiredness,
        missing_policy=missing_policy,
        **metadata,
    )


_FORCING_VARIABLES = (
    ForcingVariable(
        name="iy",
        data_type="integer",
        role="coordinate",
        unit="1",
        description="Calendar year of the interval-end timestamp",
        temporal="time",
        requiredness="baseline",
        missing_policy="forbidden",
        legacy_position=1,
    ),
    ForcingVariable(
        name="id",
        data_type="integer",
        role="coordinate",
        unit="1",
        description="Day of year of the interval-end timestamp",
        temporal="time",
        requiredness="baseline",
        missing_policy="forbidden",
        legacy_position=2,
    ),
    ForcingVariable(
        name="it",
        data_type="integer",
        role="coordinate",
        unit="h",
        description="Hour component of the interval-end timestamp",
        temporal="time",
        requiredness="baseline",
        missing_policy="forbidden",
        legacy_position=3,
    ),
    ForcingVariable(
        name="imin",
        data_type="integer",
        role="coordinate",
        unit="min",
        description="Minute component of the interval-end timestamp",
        temporal="time",
        requiredness="baseline",
        missing_policy="forbidden",
        legacy_position=4,
    ),
    _variable(
        "qn",
        "W m-2",
        "Observed net all-wave radiation",
        "observation",
        "avg",
        "conditional",
        "sentinel",
        accessor_aliases=("net_radiation", "qstar", "q_star"),
        file_aliases=("qn1_obs",),
        validation_range=(-500, 1300),
        legacy_position=5,
    ),
    _variable(
        "qh",
        "W m-2",
        "Reserved observed sensible heat-flux column; not currently consumed",
        "reserved",
        "avg",
        "optional",
        "sentinel",
        accessor_aliases=("sensible_heat", "h"),
        validation_range=(-500, 1300),
        legacy_position=6,
    ),
    _variable(
        "qe",
        "W m-2",
        "Reserved observed latent heat-flux column; not currently consumed",
        "reserved",
        "avg",
        "optional",
        "sentinel",
        accessor_aliases=("latent_heat", "le"),
        validation_range=(-500, 1300),
        legacy_position=7,
    ),
    _variable(
        "qs",
        "W m-2",
        "Observed net storage heat flux",
        "observation",
        "avg",
        "conditional",
        "sentinel",
        accessor_aliases=("storage_heat",),
        file_aliases=("qs_obs",),
        validation_range=(-100, 650),
        legacy_position=8,
    ),
    _variable(
        "qf",
        "W m-2",
        "Observed anthropogenic heat flux",
        "observation",
        "avg",
        "conditional",
        "sentinel",
        accessor_aliases=("anthropogenic_heat",),
        file_aliases=("qf_obs",),
        validation_range=(-500, 1300),
        legacy_position=9,
    ),
    _variable(
        "U",
        "m s-1",
        "Wind speed at the forcing measurement height",
        "driver",
        "inst",
        "baseline",
        "forbidden",
        accessor_aliases=("wind_speed", "wind", "u"),
        validation_range=(0.01, 60),
        legacy_position=10,
    ),
    _variable(
        "RH",
        "%",
        "Relative humidity",
        "driver",
        "inst",
        "baseline",
        "forbidden",
        accessor_aliases=("relative_humidity", "humidity", "rh"),
        validation_range=(0.0001, 105),
        legacy_position=11,
    ),
    _variable(
        "Tair",
        "degC",
        "Air temperature",
        "driver",
        "inst",
        "baseline",
        "forbidden",
        accessor_aliases=("temperature", "air_temperature", "temp", "t_air", "ta"),
        file_aliases=("temp_c",),
        validation_range=(-60, 90),
        legacy_position=12,
    ),
    _variable(
        "pres",
        "kPa",
        "Surface air pressure",
        "driver",
        "inst",
        "baseline",
        "forbidden",
        accessor_aliases=("pressure", "air_pressure", "p"),
        validation_range=(68, 130),
        runtime_unit="hPa",
        runtime_scale=10,
        legacy_position=13,
    ),
    _variable(
        "rain",
        "mm",
        "Precipitation accumulated over the forcing interval",
        "driver",
        "sum",
        "baseline",
        "forbidden",
        accessor_aliases=("precipitation", "rainfall", "precip"),
        validation_range=(0, None),
        legacy_position=14,
    ),
    _variable(
        "kdown",
        "W m-2",
        "Incoming short-wave radiation averaged over the forcing interval",
        "driver",
        "avg",
        "baseline",
        "forbidden",
        accessor_aliases=("shortwave_down", "solar_radiation", "sw_down", "k_down"),
        validation_range=(0, 1400),
        legacy_position=15,
    ),
    _variable(
        "snow",
        "1",
        "Observed surface snow-cover fraction",
        "driver",
        "inst",
        "conditional",
        "sentinel",
        accessor_aliases=("snowfall",),
        file_aliases=("snowfrac",),
        validation_range=(0, 1),
        legacy_position=16,
    ),
    _variable(
        "ldown",
        "W m-2",
        "Incoming long-wave radiation averaged over the forcing interval",
        "driver",
        "avg",
        "conditional",
        "sentinel",
        accessor_aliases=("longwave_down", "lw_down", "l_down"),
        validation_range=(100, 600),
        legacy_position=17,
    ),
    _variable(
        "fcld",
        "1",
        "Cloud fraction",
        "driver",
        "inst",
        "conditional",
        "sentinel",
        accessor_aliases=("cloud_fraction", "cloud_cover", "clouds"),
        validation_range=(0, 1),
        legacy_position=18,
    ),
    _variable(
        "Wuh",
        "mm",
        "Bulk external water use accumulated over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "sentinel",
        accessor_aliases=("water_use", "external_water", "wu_mm"),
        file_aliases=("wu_mm",),
        validation_range=(0, None),
        legacy_position=19,
    ),
    _variable(
        "xsmd",
        None,
        "Observed soil-moisture deficit input",
        "observation",
        "inst",
        "conditional",
        "sentinel",
        accessor_aliases=("soil_moisture", "smd"),
        validation_range=(0, None),
        legacy_position=20,
        unit_selector="soil_moisture_deficit",
        units_by_value={1: "m3 m-3", 2: "kg kg-1"},
    ),
    _variable(
        "lai",
        "m2 m-2",
        "Bulk observed leaf area index used as a surface fallback",
        "observation",
        "inst",
        "conditional",
        "sentinel",
        accessor_aliases=("leaf_area_index",),
        validation_range=(0, None),
        legacy_position=21,
    ),
    _variable(
        "kdiff",
        "W m-2",
        "Diffuse component of incoming short-wave radiation",
        "driver",
        "avg",
        "optional",
        "sentinel",
        accessor_aliases=("diffuse_radiation",),
        validation_range=(0, 1000),
        legacy_position=22,
    ),
    _variable(
        "kdir",
        "W m-2",
        "Direct component of incoming short-wave radiation",
        "driver",
        "avg",
        "optional",
        "sentinel",
        accessor_aliases=("direct_radiation",),
        validation_range=(0, 1400),
        legacy_position=23,
    ),
    _variable(
        "wdir",
        "degree",
        "Accepted wind-direction column; not currently consumed",
        "reserved",
        "inst",
        "optional",
        "sentinel",
        accessor_aliases=("wind_direction", "wd"),
        validation_range=(0, 360),
        legacy_position=24,
    ),
    _variable(
        "lai_evetr",
        "m2 m-2",
        "Observed leaf area index for evergreen trees",
        "observation",
        "inst",
        "conditional",
        "fallback",
        accessor_aliases=("leaf_area_index_evetr",),
        validation_range=(0, None),
        fallback="lai",
    ),
    _variable(
        "lai_dectr",
        "m2 m-2",
        "Observed leaf area index for deciduous trees",
        "observation",
        "inst",
        "conditional",
        "fallback",
        accessor_aliases=("leaf_area_index_dectr",),
        validation_range=(0, None),
        fallback="lai",
    ),
    _variable(
        "lai_grass",
        "m2 m-2",
        "Observed leaf area index for grass",
        "observation",
        "inst",
        "conditional",
        "fallback",
        accessor_aliases=("leaf_area_index_grass",),
        validation_range=(0, None),
        fallback="lai",
    ),
    _variable(
        "wuh_paved",
        "mm",
        "External water-use depth for the paved surface over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_paved",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_bldgs",
        "mm",
        "External water-use depth for the building surface over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_bldgs",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_evetr",
        "mm",
        "External water-use depth for evergreen trees over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_evetr",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_dectr",
        "mm",
        "External water-use depth for deciduous trees over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_dectr",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_grass",
        "mm",
        "External water-use depth for grass over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_grass",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_bsoil",
        "mm",
        "External water-use depth for bare soil over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_bsoil",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
    _variable(
        "wuh_water",
        "mm",
        "External water-use depth for open water over the forcing interval",
        "driver",
        "sum",
        "conditional",
        "fallback",
        file_aliases=("wu_mm_water",),
        validation_range=(0, None),
        fallback="Wuh",
    ),
)


_FORCING_REQUIREMENT_RULES = (
    RequirementRule(
        conditions={"net_radiation": (0,)},
        alternatives=(("qn",),),
        legacy_conditions={"netradiationmethod": (0,)},
    ),
    RequirementRule(
        conditions={"net_radiation": (1, 11, 100, 1001)},
        alternatives=(("ldown",),),
        legacy_conditions={"netradiationmethod": (1,)},
    ),
    RequirementRule(
        conditions={"net_radiation": (2, 12, 200, 1002)},
        alternatives=(("kdown", "fcld"),),
        legacy_conditions={"netradiationmethod": (2,)},
    ),
    RequirementRule(
        conditions={"net_radiation": (3, 13, 300, 1003)},
        alternatives=(("kdown",),),
        legacy_conditions={"netradiationmethod": (3,)},
    ),
    RequirementRule(
        conditions={"storage_heat": (0,)},
        alternatives=(("qs",),),
        legacy_conditions={"storageheatmethod": (0,)},
    ),
    RequirementRule(
        conditions={"emissions": (0,)},
        alternatives=(("qf",),),
        legacy_conditions={"emissionsmethod": (0,)},
    ),
    RequirementRule(
        conditions={"soil_moisture_deficit": (1, 2)},
        alternatives=(("xsmd",),),
        legacy_conditions={"smdmethod": (1, 2)},
    ),
    RequirementRule(
        conditions={"laimethod": (0,)},
        alternatives=(("lai",), ("lai_evetr", "lai_dectr", "lai_grass")),
        legacy_conditions={"laimethod": (0,)},
    ),
    RequirementRule(
        conditions={"water_use": (1,)},
        alternatives=(
            ("Wuh",),
            (
                "wuh_paved",
                "wuh_bldgs",
                "wuh_evetr",
                "wuh_dectr",
                "wuh_grass",
                "wuh_bsoil",
                "wuh_water",
            ),
        ),
    ),
    RequirementRule(
        conditions={"snow_use": (1,), "net_radiation": (0,)},
        alternatives=(("snow",),),
        legacy_conditions={"snowuse": (1,), "netradiationmethod": (0,)},
    ),
)


FORCING_REGISTRY = ForcingRegistry(
    variables=_FORCING_VARIABLES,
    requirement_rules=_FORCING_REQUIREMENT_RULES,
)
