"""Regenerate the one-month short sample fixture from the shipped sample data.

The shipped sample (``supy/sample_data/``) is a full year: 8784 hourly forcing
rows, disaggregated to 105408 five-minute rows on every
``SUEWSSimulation`` construction. Lifecycle tests need a working simulation,
not a year of climate, so this module carves January 2012 out of it and
rewrites the config to match.

The two generated artefacts are committed beside this module:

- ``Kc_2012_data_60_jan.txt`` - the header plus the 744 hourly rows whose
  interval ends inside January 2012 (the file stamps each row at the END of
  its interval, so the last row is ``2012 32 0 0``, midnight on 1 February).
- ``sample_config_short.yml`` - the shipped ``sample_config.yml`` with only
  four lines changed: ``name``, ``description``, ``model.control.end_time``
  and the forcing ``file`` value. Everything else, physics included, is
  byte-identical to the shipped sample, so the short fixture exercises the
  same model configuration.

``test/core/test_sample_short_fixture.py`` runs this module's ``build``
against the shipped sample and fails if either committed artefact differs,
so the fixture cannot drift when the sample data changes. Regenerate with:

    python test/fixtures/sample_short/make_sample_short.py
"""

from __future__ import annotations

from importlib.resources import as_file
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parent

FORCING_NAME = "Kc_2012_data_60_jan.txt"
CONFIG_NAME = "sample_config_short.yml"

# January 2012 in the sample forcing's end-of-interval day-of-year stamping:
# the first row is (id=1, it=1) and the last is (id=32, it=0), midnight on
# 1 February. 744 rows, one per hour.
LAST_DAY_OF_YEAR = 32
SHORT_END_TIME = "2012-01-31"
SHORT_NAME = "sample_config_short"
SHORT_DESCRIPTION = (
    "One month (January 2012) of the shipped sample configuration, for tests "
    "that need a working simulation rather than a year of climate. "
    "Generated by test/fixtures/sample_short/make_sample_short.py."
)


def _sample_dir():
    """Yield the shipped sample-data directory as a real filesystem path."""
    from supy._env import trv_supy_module

    return as_file(trv_supy_module / "sample_data")


def build_forcing(text_full: str) -> str:
    """Return the January-only forcing text carved from the full-year text."""
    lines = text_full.splitlines()
    header, rows = lines[0], lines[1:]
    kept = []
    for row in rows:
        if not row.strip():
            continue
        fields = row.split()
        day_of_year, hour = int(fields[1]), int(fields[2])
        if day_of_year > LAST_DAY_OF_YEAR:
            break
        if day_of_year == LAST_DAY_OF_YEAR and hour > 0:
            break
        kept.append(row)
    return "\n".join([header, *kept]) + "\n"


def build_config(text_full: str) -> str:
    """Return the short config text: the shipped config with four lines changed.

    Rewritten line by line rather than through a YAML round-trip so the
    committed fixture keeps the shipped file's comments, key order and
    formatting, and so a reader can diff the two and see exactly what the
    short fixture changes.
    """
    out = []
    for line in text_full.splitlines():
        stripped = line.strip()
        if stripped.startswith("name:") and not line.startswith(" "):
            out.append(f"name: {SHORT_NAME}")
        elif stripped.startswith("description:") and not line.startswith(" "):
            out.append(f"description: {SHORT_DESCRIPTION}")
        elif stripped.startswith("end_time:"):
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f'{indent}end_time: "{SHORT_END_TIME}"')
        elif stripped.startswith("value:") and stripped.endswith("Kc_2012_data_60.txt"):
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}value: {FORCING_NAME}")
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def build() -> dict[str, str]:
    """Return ``{filename: text}`` for both artefacts, from the shipped sample."""
    with _sample_dir() as path_sample:
        text_forcing = (path_sample / "Kc_2012_data_60.txt").read_text(encoding="utf-8")
        text_config = (path_sample / "sample_config.yml").read_text(encoding="utf-8")
    return {
        FORCING_NAME: build_forcing(text_forcing),
        CONFIG_NAME: build_config(text_config),
    }


def main() -> None:
    for name, text in build().items():
        (FIXTURE_DIR / name).write_text(text, encoding="utf-8")
        print(f"[OK] wrote {name}")


if __name__ == "__main__":
    main()
