#!/usr/bin/env python3
"""Guard: PRs touching data_model / cmd should rebuild the knowledge pack
(gh#1406).

The SUEWS knowledge pack ships under
``src/supy/knowledge/pack/current/`` after a meson build. It must be
generated from the same source tree as the wheel, otherwise
``query_knowledge`` can answer from chunks that no longer match the
live schema.

Usage
-----
    python scripts/lint/check_knowledge_pack_freshness.py [--base BASE_REF]

Compares the diff between BASE_REF (default ``origin/master``) and the
current tree (or HEAD in CI). If any file under ``src/supy/data_model/``
or ``src/supy/cmd/`` changed, the audit verifies that a current
knowledge pack can be produced for HEAD. When generated artefacts are
committed, it additionally requires the committed ``content_hash`` to
move with the guarded source changes.

Bypassing
---------
If the diff is genuinely cosmetic (docstring-only edits, comment
reformats), a maintainer can add the ``0-ci:knowledge-pack-audit-ok`` label
to the PR. The companion workflow short-circuits when that label is
present.

When the generated pack is committed, this script checks that the
committed manifest's ``content_hash`` moved in the same PR as the
data_model / cmd diff. In the normal SUEWS repository state the pack
artefacts are not tracked; in that case the script performs a temporary
local pack build and checks that the generated manifest is bound to
HEAD.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Paths whose changes should normally trigger a pack rebuild. The pack
# build globs much wider than this (every file under src/suews/src,
# src/suews_bridge/src, src/supy), but those non-Python paths usually
# move via deliberate releases. The two paths we guard here are the
# ones most likely to drift silently in routine PR work.
_GUARDED_ROOTS = (
    "src/supy/data_model/",
    "src/supy/cmd/",
)

_MANIFEST_RELATIVE = "src/supy/knowledge/pack/current/manifest.json"


def _changed_files(base_ref: str) -> list[str]:
    out = subprocess.check_output(
        ["git", "diff", "--name-only", f"{base_ref}...HEAD"],
        cwd=REPO_ROOT,
        text=True,
    )
    return [line.strip() for line in out.splitlines() if line.strip()]


def _read_committed_manifest_hash(ref: str) -> str | None:
    """Read ``content_hash`` from the manifest at ``ref``, or ``None``
    when the manifest is not committed at that ref (the standard case
    — packs are normally regenerated by meson, not tracked in git).
    """
    try:
        text = subprocess.check_output(
            ["git", "show", f"{ref}:{_MANIFEST_RELATIVE}"],
            cwd=REPO_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return None
    try:
        manifest = json.loads(text)
    except json.JSONDecodeError:
        return None
    return manifest.get("content_hash")


def _current_head() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        text=True,
    ).strip()


def _build_temporary_manifest() -> dict:
    """Build the knowledge pack into a temporary directory and return its manifest."""
    with tempfile.TemporaryDirectory(prefix="suews-knowledge-pack-audit-") as tmp:
        output_dir = Path(tmp)
        result = subprocess.run(
            [
                sys.executable,
                str(REPO_ROOT / "src" / "supy" / "knowledge" / "pack.py"),
                str(REPO_ROOT),
                str(output_dir),
                "--command",
                "knowledge-pack freshness audit",
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "temporary pack build failed with exit "
                f"{result.returncode}; stdout={result.stdout!r}; "
                f"stderr={result.stderr!r}"
            )
        return json.loads(
            (output_dir / "manifest.json").read_text(encoding="utf-8")
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--base",
        default="origin/master",
        help="Base ref to compare against (default origin/master).",
    )
    args = parser.parse_args(argv)

    changed = _changed_files(args.base)
    guarded_changes = [
        path for path in changed if any(path.startswith(root) for root in _GUARDED_ROOTS)
    ]
    if not guarded_changes:
        # Nothing under the guarded roots changed; pack is unaffected.
        return 0

    base_hash = _read_committed_manifest_hash(args.base)
    head_hash = _read_committed_manifest_hash("HEAD")

    if base_hash is None and head_hash is None:
        # Pack is not tracked in git at either ref (the normal SUEWS
        # state — meson regenerates per build). Since there is no committed
        # content_hash to compare, do the next-best deterministic check:
        # rebuild into a temp dir and verify the generated manifest binds to
        # this exact HEAD.
        try:
            manifest = _build_temporary_manifest()
            head_sha = _current_head()
        except Exception as exc:  # noqa: BLE001 - report audit failure verbatim
            print(
                "Knowledge-pack freshness check FAILED.\n\n"
                "The pack is not committed to git, and a temporary rebuild "
                f"failed: {exc}",
                file=sys.stderr,
            )
            return 1

        if manifest.get("git_sha") != head_sha:
            print(
                "Knowledge-pack freshness check FAILED.\n\n"
                "Temporary rebuild produced a manifest for git_sha "
                f"{manifest.get('git_sha')!r}, but HEAD is {head_sha!r}.",
                file=sys.stderr,
            )
            return 1
        if not manifest.get("content_hash") or not manifest.get("chunk_count"):
            print(
                "Knowledge-pack freshness check FAILED.\n\n"
                "Temporary rebuild produced an incomplete manifest "
                f"(content_hash={manifest.get('content_hash')!r}, "
                f"chunk_count={manifest.get('chunk_count')!r}).",
                file=sys.stderr,
            )
            return 1
        print(
            "Knowledge-pack freshness check: temporary rebuild succeeded "
            f"for HEAD {head_sha[:10]} with content_hash "
            f"{manifest.get('content_hash')}.",
            file=sys.stderr,
        )
        return 0

    if base_hash == head_hash:
        guarded_list = "\n  - ".join(guarded_changes[:10])
        print(
            f"Knowledge-pack freshness check FAILED.\n\n"
            f"The following files under guarded roots changed in this PR:\n"
            f"  - {guarded_list}\n"
            f"\nbut the committed knowledge pack's content_hash did not "
            f"move: {head_hash}.\n\n"
            f"Run `suews knowledge build --output "
            f"src/supy/knowledge/pack/current --repo-root .` and commit "
            f"the resulting manifest.json + chunks.jsonl.gz, or apply "
            f"the `0-ci:knowledge-pack-audit-ok` label if the diff is "
            f"genuinely cosmetic (docstring / comment only).",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
