#!/usr/bin/env python3
"""Guard: PRs touching data_model / cmd should rebuild the knowledge pack
(gh#1406).

The SUEWS knowledge pack ships under
``src/supy/knowledge/pack/current/`` after a meson build. Its meson
``custom_target`` declares only ``knowledge/pack.py`` as a dependency,
so changes under ``src/supy/data_model/`` or ``src/supy/cmd/`` do NOT
trigger an automatic rebuild. The result: the installed pack drifts
from HEAD and ``query_knowledge`` answers reference fields/code that
no longer match the live schema.

Usage
-----
    python scripts/lint/check_knowledge_pack_freshness.py [--base BASE_REF]

Compares the diff between BASE_REF (default ``origin/master``) and the
current tree (or HEAD in CI). If any file under ``src/supy/data_model/``
or ``src/supy/cmd/`` changed *and* the pack's ``content_hash`` did not,
exit non-zero with remediation guidance.

Bypassing
---------
If the diff is genuinely cosmetic (docstring-only edits, comment
reformats), a maintainer can add the ``knowledge-pack-audit-ok`` label
to the PR. The companion workflow short-circuits when that label is
present.

This script does NOT itself rebuild the pack — that requires a full
build environment with Fortran toolchain. It only checks that the
committed pack manifest's ``content_hash`` was bumped in the same
PR as the data_model / cmd diff.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Paths whose changes should normally trigger a pack rebuild. The pack
# build globs much wider than this (every file under src/suews/src,
# src/suews_bridge/src, src/supy), but those non-Python paths usually
# move via deliberate releases. The two paths we guard here are the
# ones most likely to drift silently in routine PR work.
_GUARDED_ROOTS = (
    "src/supy/data_model/",
    "src/supy/cmd/",
)

_MANIFEST_RELATIVE = "src/supy/knowledge/pack/current/manifest.json"


def _changed_files(base_ref: str) -> list[str]:
    out = subprocess.check_output(
        ["git", "diff", "--name-only", f"{base_ref}...HEAD"],
        cwd=REPO_ROOT,
        text=True,
    )
    return [line.strip() for line in out.splitlines() if line.strip()]


def _read_committed_manifest_hash(ref: str) -> str | None:
    """Read ``content_hash`` from the manifest at ``ref``, or ``None``
    when the manifest is not committed at that ref (the standard case
    — packs are normally regenerated by meson, not tracked in git).
    """
    try:
        text = subprocess.check_output(
            ["git", "show", f"{ref}:{_MANIFEST_RELATIVE}"],
            cwd=REPO_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return None
    try:
        manifest = json.loads(text)
    except json.JSONDecodeError:
        return None
    return manifest.get("content_hash")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--base",
        default="origin/master",
        help="Base ref to compare against (default origin/master).",
    )
    args = parser.parse_args(argv)

    changed = _changed_files(args.base)
    guarded_changes = [
        path for path in changed if any(path.startswith(root) for root in _GUARDED_ROOTS)
    ]
    if not guarded_changes:
        # Nothing under the guarded roots changed; pack is unaffected.
        return 0

    base_hash = _read_committed_manifest_hash(args.base)
    head_hash = _read_committed_manifest_hash("HEAD")

    if base_hash is None and head_hash is None:
        # Pack is not tracked in git at either ref (the normal SUEWS
        # state — meson regenerates per build). We cannot use a
        # commit-time hash compare; surface guidance only.
        print(
            "Knowledge-pack freshness check: data_model / cmd changes "
            "detected but the pack is not committed to git in this "
            "repository. The local meson build only rebuilds the pack "
            "when knowledge/pack.py itself changes — touching "
            "data_model/ or cmd/ is not enough. Confirm a fresh "
            "`make dev` (or `suews knowledge build`) was run before "
            "shipping.",
            file=sys.stderr,
        )
        return 0

    if base_hash == head_hash:
        guarded_list = "\n  - ".join(guarded_changes[:10])
        print(
            f"Knowledge-pack freshness check FAILED.\n\n"
            f"The following files under guarded roots changed in this PR:\n"
            f"  - {guarded_list}\n"
            f"\nbut the committed knowledge pack's content_hash did not "
            f"move: {head_hash}.\n\n"
            f"Run `suews knowledge build --output "
            f"src/supy/knowledge/pack/current --repo-root .` and commit "
            f"the resulting manifest.json + chunks.jsonl.gz, or apply "
            f"the `knowledge-pack-audit-ok` label if the diff is "
            f"genuinely cosmetic (docstring / comment only).",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
