"""Generate forcing-variable reference documentation from the registry."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

try:
    from supy.data_model.forcing import FORCING_REGISTRY, ForcingRequirement
    from supy.data_model.schema.interfaces import DATA_INTERFACE_VERSION
except ImportError as exc:
    print(
        "ERROR: Cannot import supy. Run 'make dev' before building the docs.",
        file=sys.stderr,
    )
    print(f"Import error: {exc}", file=sys.stderr)
    sys.exit(1)


def _physics_text(variable) -> str:
    conditions = []
    for requirement in variable.physics_requirements:
        values = ", ".join(str(value) for value in requirement.values)
        conditions.append(f"``{requirement.field}`` in {{{values}}}")
    return "; ".join(conditions) or "-"


def _requirement_text(variable) -> str:
    labels = {
        ForcingRequirement.DATETIME: "datetime baseline",
        ForcingRequirement.BASELINE: "baseline",
        ForcingRequirement.CONDITIONAL: "physics-conditional",
        ForcingRequirement.OPTIONAL: "optional",
        ForcingRequirement.DERIVED: "derived",
    }
    return labels[variable.requirement]


def _range_text(variable) -> str:
    if variable.valid_range is None:
        return "-"
    minimum = (
        "-infinity"
        if variable.valid_range.minimum is None
        else f"{variable.valid_range.minimum:g}"
    )
    maximum = (
        "infinity"
        if variable.valid_range.maximum is None
        else f"{variable.valid_range.maximum:g}"
    )
    return f"[{minimum}, {maximum}] ``{variable.unit}``"


def _format_variable(variable) -> list[str]:
    title = variable.name
    lines = [
        f".. _forcing-variable-{variable.name.casefold()}:",
        "",
        f".. rubric:: {title}",
        "",
        variable.description,
        "",
        f":Unit: ``{variable.unit}``",
        f":Data type: ``{variable.data_type.value}``",
        f":Temporal semantics: ``{variable.temporal_semantics.value}``",
        f":Requirement: {_requirement_text(variable)}",
        f":Missing-value policy: ``{variable.missing_value_policy.value}``",
        f":Valid range: {_range_text(variable)}",
    ]
    if variable.aliases:
        aliases = ", ".join(f"``{alias}``" for alias in variable.aliases)
        lines.append(f":Aliases: {aliases}")
    if variable.physics_requirements:
        lines.append(f":Required when: {_physics_text(variable)}")
    if variable.missing_value is not None:
        lines.append(f":Optional missing value: ``{variable.missing_value:g}``")
    if variable.surface_suffixes:
        columns = ", ".join(
            f"``{variable.name.casefold()}_{suffix}``"
            for suffix in variable.surface_suffixes
        )
        lines.append(f":Per-land-cover columns: {columns}")
    if variable.legacy_position is not None:
        lines.append(f":Legacy position: {variable.legacy_position}")
    if not variable.input_column:
        lines.append(":Input column: No; generated by the loader")
    lines.append("")
    return lines


def generate_rst(output_dir: Path) -> Path:
    """Write the complete forcing-variable reference page."""
    output_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        ".. This file is generated by docs/generate_forcing_variable_rst.py.",
        ".. Do not edit it directly.",
        "",
        ".. _forcing-variable-reference:",
        "",
        "Forcing Variable Reference",
        "==========================",
        "",
        "This reference is generated from the same typed registry used by the",
        "Python forcing loader and physics pre-flight validation. The published",
        f"data-interface version is ``{DATA_INTERFACE_VERSION}``.",
        "",
        "Machine-readable forms are available from the command line:",
        "",
        ".. code-block:: console",
        "",
        "   suews schema --kind forcing --artifact schema --format json",
        "   suews schema --kind forcing --artifact catalogue --format json",
        "",
        "Versioning and compatibility",
        "----------------------------",
        "",
        "The forcing and output catalogues share an independent semantic version.",
        "A major increment permits incompatible metadata or naming changes; a minor",
        "increment adds variables or metadata without invalidating existing consumers;",
        "and a patch increment corrects metadata without changing its structure.",
        "Each catalogue also records the configuration-schema version used to build it.",
        "",
        "Requirement summary",
        "-------------------",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 12 16 14 14 44",
        "",
        "   * - Column",
        "     - Requirement",
        "     - Unit",
        "     - Temporal",
        "     - Physics condition",
    ]
    for variable in FORCING_REGISTRY.variables:
        lines.extend([
            f"   * - ``{variable.name}``",
            f"     - {_requirement_text(variable)}",
            f"     - ``{variable.unit}``",
            f"     - ``{variable.temporal_semantics.value}``",
            f"     - {_physics_text(variable)}",
        ])

    lines.extend([
        "",
        "Definitions",
        "-----------",
        "",
        "``avg`` values are averages over the interval ending at the timestamp;",
        "``sum`` values are accumulated over that interval; ``inst`` values are",
        "instantaneous at the timestamp; and ``time`` fields describe the timestamp.",
        "",
    ])
    for variable in FORCING_REGISTRY.variables:
        lines.extend(_format_variable(variable))

    output_path = output_dir / "index.rst"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {output_path}")
    print(f"Total variables documented: {len(FORCING_REGISTRY.variables)}")
    return output_path


def main() -> None:
    """Generate forcing-variable RST from command-line arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("source/inputs/forcing-variables"),
    )
    args = parser.parse_args()
    generate_rst(args.output_dir)


if __name__ == "__main__":
    main()
