"""Generate the forcing-variable reference fragment from its registry."""

from __future__ import annotations

import argparse
from pathlib import Path

from supy.data_model.forcing import FORCING_REGISTRY


def _display(value: str | None) -> str:
    """Return a compact RST-safe table value."""
    if value is None:
        return "Unresolved"
    return value.replace("`", "\\`")


def render_forcing_reference() -> str:
    """Return deterministic RST projected from the forcing registry."""
    lines = [
        ".. This file is generated by docs/generate_forcing_variable_rst.py.",
        ".. Do not edit it directly.",
        "",
        "The table below is generated from the forcing registry. It records input",
        "units and current Python semantics; unresolved scientific metadata is",
        "labelled explicitly rather than inferred.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 14 12 12 14 14 34",
        "",
        "   * - Column",
        "     - Input unit",
        "     - Temporal class",
        "     - Requiredness",
        "     - Missing policy",
        "     - Description",
    ]
    for variable in FORCING_REGISTRY.variables:
        lines.extend([
            f"   * - ``{variable.name}``",
            f"     - {_display(variable.unit)}",
            f"     - ``{variable.temporal}``",
            f"     - ``{variable.requiredness}``",
            f"     - ``{variable.missing_policy}``",
            f"     - {_display(variable.description)}",
        ])
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the generated reference fragment."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    content = render_forcing_reference()
    if args.output is None:
        print(content, end="")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
