name: Debug cibuildwheel with SSH

# Manual workflow for debugging cibuildwheel build issues with SSH access
# Usage: Actions tab → "Debug cibuildwheel with SSH" → Run workflow → Select options
# SSH sessions are restricted to the workflow actor for security

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to debug'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-13      # Intel Mac
          - macos-latest  # Apple Silicon Mac
          - windows-2025
      python_version:
        description: 'Python version (cpXX format)'
        required: true
        default: 'cp312'
        type: choice
        options:
          - cp39   # Python 3.9
          - cp310  # Python 3.10
          - cp311  # Python 3.11
          - cp312  # Python 3.12
          - cp313  # Python 3.13
      arch:
        description: 'Architecture'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64  # Linux/macOS 64-bit
          - arm64   # macOS Apple Silicon
          - AMD64   # Windows 64-bit
          - x86     # Windows 32-bit
      debug_mode:
        description: 'SSH debug mode'
        required: true
        default: 'before-build'
        type: choice
        options:
          - before-build   # SSH before cibuildwheel starts
          - after-failure  # SSH only if build fails
          - always         # SSH both before and after
          - disabled       # No SSH, just run build

jobs:
  debug_build:
    name: Debug ${{ inputs.python_version }} on ${{ inputs.platform }} (${{ inputs.arch }})
    runs-on: ${{ inputs.platform }}
    
    env:
      # Build selection based on inputs
      CIBW_BUILD: ${{ inputs.python_version }}-${{ inputs.platform == 'ubuntu-latest' && 'manylinux' || inputs.platform == 'windows-2025' && 'win' || 'macosx' }}*
      CIBW_ARCHS: ${{ inputs.arch }}
      
      # Linux settings
      CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
      
      # macOS: Install gfortran
      CIBW_BEFORE_ALL_MACOS: >
        brew install gfortran &&
        brew unlink gfortran &&
        brew link gfortran
        
      # Windows: Install MSYS2 toolchain
      CIBW_BEFORE_ALL_WINDOWS: >
        C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm" &&
        C:\msys64\usr\bin\bash.exe -lc "pacman -S --needed --noconfirm mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gcc-fortran mingw-w64-ucrt-x86_64-binutils mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-openblas"
        
      # Windows build environment
      CIBW_ENVIRONMENT_WINDOWS: >
        PATH="C:\\msys64\\ucrt64\\bin;$PATH"
        CC=gcc
        CXX=g++
        FC=gfortran
        CFLAGS="-D__USE_MINGW_ANSI_STDIO=1 -mlong-double-64"
        CXXFLAGS="-D__USE_MINGW_ANSI_STDIO=1 -mlong-double-64"
        FCFLAGS="-fno-optimize-sibling-calls"
        LDFLAGS="-lucrt -static-libgcc -static-libgfortran -LC:/msys64/ucrt64/lib -lsetjmp_compat"
        
      # Windows: Create setjmp compatibility library
      CIBW_BEFORE_BUILD_WINDOWS: >
        echo Creating setjmp compatibility library... &&
        echo int _setjmpex(void* buf) { extern int __intrinsic_setjmpex(void*); return __intrinsic_setjmpex(buf); } > setjmp_compat.c &&
        C:\msys64\ucrt64\bin\gcc.exe -c setjmp_compat.c -o setjmp_compat.o &&
        C:\msys64\ucrt64\bin\ar.exe rcs libsetjmp_compat.a setjmp_compat.o &&
        echo Library created, checking contents: &&
        C:\msys64\ucrt64\bin\nm.exe libsetjmp_compat.a &&
        echo Copying to standard locations: &&
        copy libsetjmp_compat.a C:\msys64\ucrt64\lib\ &&
        copy libsetjmp_compat.a C:\msys64\ucrt64\x86_64-w64-mingw32\lib\ &&
        echo Verifying library locations: &&
        dir C:\msys64\ucrt64\lib\libsetjmp_compat.a &&
        dir C:\msys64\ucrt64\x86_64-w64-mingw32\lib\libsetjmp_compat.a &&
        where python &&
        where gcc &&
        gcc --version &&
        pip install delvewheel
        
      CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
      
      # Test configuration
      CIBW_TEST_REQUIRES: pytest
      CIBW_TEST_COMMAND_MACOS: "python -m pytest '{project}/test'"
      CIBW_TEST_COMMAND_LINUX: "python -m pytest '{project}/test'"
      CIBW_TEST_COMMAND_WINDOWS: "python -m pytest {project}\\test"
      
      # macOS deployment target
      MACOSX_DEPLOYMENT_TARGET: ${{ inputs.platform == 'macos-13' && '13.0' || '14.0' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      # Install Node.js for Claude Code CLI
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20 for better compatibility
          
      # Install Claude Code CLI for AI-assisted debugging
      - name: Install Claude Code
        run: |
          echo "Installing Claude Code CLI..."
          npm install -g @anthropic-ai/claude-code
          claude doctor || echo "Claude doctor check completed"
          
      # SSH debug session BEFORE build
      - name: Pre-build SSH Debug Session
        if: inputs.debug_mode == 'before-build' || inputs.debug_mode == 'always'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        timeout-minutes: 60
        
      - name: Build environment info
        run: |
          echo "=== Build Configuration ==="
          echo "Platform: ${{ inputs.platform }}"
          echo "Python: ${{ inputs.python_version }}"
          echo "Architecture: ${{ inputs.arch }}"
          echo "CIBW_BUILD: ${{ env.CIBW_BUILD }}"
          echo "CIBW_ARCHS: ${{ env.CIBW_ARCHS }}"
          echo ""
          echo "=== System Info ==="
          python --version
          pip --version
          
      # Build with verbose logging, continue on error to allow post-failure debugging
      - name: Build wheels with verbose output
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_BUILD_VERBOSITY: 3  # Maximum verbosity
        continue-on-error: true
        id: build
        
      # SSH debug session AFTER build (on failure or always)
      - name: Post-failure SSH Debug Session
        if: (failure() && inputs.debug_mode == 'after-failure') || inputs.debug_mode == 'always'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        timeout-minutes: 60
        
      # Upload all logs and build artifacts for analysis
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs-${{ inputs.platform }}-${{ inputs.python_version }}-${{ inputs.arch }}
          path: |
            cibuildwheel*.log
            build/
            dist/
            wheelhouse/
            
      - name: Upload wheels (if successful)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ inputs.platform }}-${{ inputs.python_version }}-${{ inputs.arch }}
          path: ./wheelhouse/*.whl