name: Fortran_prettify

on:
  # File paths to consider in the event. Optional; defaults to all
  push:
    branches:
      - '**'  # Run on all branches
      - '!master'  # Exclude master branch
    paths:       # Push events containing matching files
      - 'src/suews/src/*'
      - '.github/workflows/fprettify.yml'

jobs:
  fprettify:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        submodules: true

    - name: Setup Python for use with actions
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Version range or exact version of a Python version to use, using semvers version range syntax.

    - name: install fprettify
      run: |
        pip install fprettify -U
        make pip

    - name: format Fortran code
      run: fprettify src/suews/src/*f95 -c .fprettify.yml

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'src/suews/src/*f95'
        message: "[GH Actions] fprettify source code"





